### ISSUE TITLE
Zoom Limiter für sehr kurze Projekte

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#1]
der zoom Limiter produziert derzeit noch ein Problem bei neuen Aufnahmen. Vorgehen: ich starte ein leeres Projekt, der Zoom ist recht weit draußen. Ich starte die Aufnahme, der Aufnahmebalken kriecht nur wenig von der Stelle. Ich zoome rein um zu schauen, dass da wirklich alles seine Ordnung hat - und kann nicht mehr zurück zoomen auf eine mittlere Stufe, da das Projekt eben noch sehr kurz ist.
Man kann natürlich mit alt+zoom das umgehen, besser wäre es aber, eine sinnvolle Untergrenze zu definieren unter der der Zoomlimiter nicht zuschlägt. Sprich - man kann immer bis 5 Minuten rauszoomen oder so was.

Standardmäßig startet eine Aufnahme mit einer Ansicht von 3 Minuten, mindestens bis dahin sollte man also immer heraus-zoomen können.

**Comment by mespotine** [comment]
Pfeiltaste runter hat ja gar keinen Zoomlimiter. Soll das so und wenn ja, warum?

**Comment by rstockm** [comment]
@mespotine ich habe die Pfeiltaste nach unten hinzugefügt, das macht schon mehr Sinn. Problem aber: Dein Fix funktioniert gut für die Tastatur, mit der der Pinch-to-Zoom Geste auf dem Trackpad  jedoch ist es unverändert so, dass der Zoomlimiter zu früh greift.

**Comment by mespotine** [comment]
Kann ich leider nicht hacken, da ich kein Trackpad habe....
Aber im Prinzip müsste die eine Zeile (mit GetProjectLength und <180 drin) sich auch in das andere Skript einbauen lassen können...

**Comment by mespotine** [comment]
Ich hatte da mal versucht was zu hacken, wenn ich mich erinnere, aber das gab lauter Probleme. Hatte es aber nur mit MouseWheel testen können und nicht mit Trackpad...

**Comment by rstockm** [comment]
Öhm. Wieso sind das zwei Skripte und nicht eines? Wo ist denn das zweite?

**Comment by mespotine** [comment]
ultraschall_zoomlimiter.lua das sowohl zoom in als auch zoom out macht für pinch.

ultraschall_zoom_out_limiter.lua macht nur zoom out(und ist das, was ich gehackt habe)

Die ähnlichen Namen sind etwas unglücklich, aber mir fiel da auch nie was besseres ein...

**Comment by mespotine** [comment]
Reaper macht bei MultiZoom leider keinen Unterschied zwischen rein und rauszoomen, zumindest nicht von den Keybindings her, daher müssen wir in einem Script Beides machen. 
Im Gegensatz zu den normalen Shortcut-tasten, wo wir flexibler sind und die Usecases sauber voneinander trennen können...

**Comment by rstockm** [comment]
Hm okay. Ich schaue mir das nochmal genauer an.

**Comment by rstockm** [comment]
So, ich habe das jetzt auch für das Trackpad eingestellt: scheint gut zu laufen. Kann das abschließend jetzt nochmal wer mit einem Mausrad testen?

**Comment by mespotine** [comment]
Mach ich morgen nachmittag denn...

**Comment by mespotine** [comment]
Pfeiltaste runter hatte kurioserweise immer noch keinen Zoomlimiter. Habs nun ergänzt und sollte(TM) jetzt funzen.

Mousewheel (und auch Pfeiltaste runter/-) haben aber während REC ein Problem. Sie limitieren zwar, aber forcieren den Playcursor in die Mitte. 
Da dieser am Ende des Projekts ist, heißt das soviel wie, dass das gesamte Projekt bis zur Mitte des Arrangeview angezeigt wird, wobei dieses "Mitte" durchaus weiter rechts, als auch weiter links sein kann.
Das war auch der Grund, weshalb ich das Hacken daran aufgegeben hatte. Ich hatte einfach nicht herausbekommen, woran das liegt.
Vermutlich irgendwo ein Setting für während Rec, dass da Einfluss hat.


![mousewheel-zoomlimiter-problem](https://user-images.githubusercontent.com/4251851/37291022-16809434-260e-11e8-897b-b2a48c8ca1ea.gif)

**Comment by rstockm** [comment]
Das beschriebene Verhalten würde ich als das Gewünschte bezeichnen.
Ich habe noch den Pfeil-Rauf mit aufgenommen, der zentriert jetzt genauso auf den Edit-Cursor.
Ich musste nochmal einen neuen Branch für die Änderungen anlegen, da der alte nicht mehr sinnvoll zu mergen war: zu weit vom Master entfernt in bezug auf die keyb.ini :-(
