### ISSUE TITLE
Plausibilitätschecks vorm Rendern

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#102]
Bevor man den Render-Dialog öffnet, sollte Ultraschall prüfen, ob Tracks gemutet sind und dann nachfragen, ob das so sein soll.
Damit kann man verhindern, dass man aus Versehen einen Sprechenden gemutet hat und dadurch der Podcast unhörbar ist.
Abschaltbar muss es natürlich sein.

**Comment by rstockm** [comment]
Die Frage ist, ob man hierfür wirklich einen Daemon-Job braucht oder ob man das nicht ganz entspannt in das Skript für den Export-Assistenten einbaut sowie in den Render-Button. Ich wäre für letzteres.

**Comment by rstockm** [comment]
Gelöst mit
https://github.com/Ultraschall/ultraschall-portable/commit/d2a679f58c332c57bdcb62dd112f7ff311518787
