### ISSUE TITLE
Beim Eingeben von Metadaten sollte man auch Kommas eingeben können

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#116]
Beim Eingeben von Metadaten sollte man auch Kommas eingeben können.

Das Script ultraschall_edit_id3_tags.lua muss dafür geändert werden.

Braucht Reaper 5.979 um zu funktionieren.

**Comment by rstockm** [comment]
Sollte gleich mit gemacht werden:

https://github.com/Ultraschall/ultraschall-portable/issues/167

**Comment by heikopanjas** [comment]
Hier ist mWn noch der Trenner offen. Schlage `@@` vor.

**Comment by mespotine** [comment]
Hatte \b genommen.

**Comment by heikopanjas** [comment]
*Hatte* oder *habe*? Wenn in die 4.0 Beta `\b` reinsoll, brauche ich bis spätestens heute am frühen abend ein Theme, in dem der `\b`-Code drin ist.

**Comment by mespotine** [comment]
Im Plugin muss dafür nichts nachgehackt werden, das sollte alles weiter funzen. Wenn nicht, hier kurz reinposten und dann fix ichs auf Lua Seite.

**Comment by mespotine** [comment]
Wird gelöst durch #120
