### ISSUE TITLE
Move left/right to next edge Verhalten erweitern

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#122]
Die Funktionen "Move left/right to next edge" (ALT+UP/DOWN) sollen erweitert werden.
Wenn ein oder mehrere Items markiert sind, dann soll an den Anfang des ersten Items bzw. an das Ende des letzen Items gesprungen werden.

**Comment by mespotine** [comment]
Modifiziere mal in diesem Branch:
https://github.com/Ultraschall/ultraschall-portable/tree/%2317-Ultraschall-Portable_Januar2019-SpringZuSinnvollenElementen

**Comment by rstockm** [comment]
Ja, gute Idee. Und dann kommt das auch gleich auf `alt`+`links`/`rechts`
