### ISSUE TITLE
Ripple Cut: während play springt der Playcursor um Zeitselektion zurück

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#13]
Wenn ich mit RippleCut etwas rausschneide und Play anhabe:
Derzeitiges Verhalten ist, es wird was rausgeschnitten, wobei das Audio um die Länge der Zeitauswahl nach vorn wandert. Gleichzeitig bleibt der Playcursor aber noch an der "alten" Stelle, was dazu führt, dass man im Projekt plötzlich quasi nach vor springt. Um nun weiter zu hören, muss man den Playcursor extra wieder an eine frühere Projektposition verschieben, um den Ripple-Cut-Zeitbereich wieder auszugleichen.

Es sollte stattdessen der Playcursor mindestens um die Zeitauswahllänge zurückspringen.
Auf diese Art muss man nicht erst wieder zurückspringen nach dem Schneiden, sondern setzt das Abspielen am selben inhaltlichen Punkt wieder an.
Speziell wenn man wenige Schnitte hat in einem Projekt, man dafür aber das gesamte Projekt durchhören muss(oder nochmal will), kann man den Schnitt quasi in einmal Projektlänge durchführen mit nur noch Verwendung von RippleCut während Play.

Reduziert die Anzahl unsinniger Klicks enorm...

**Comment by rstockm** [comment]
Oh ja, klingt extrem sinnvoll. Nicht komplett trivial, da man erst mal die Länge des zu schneidenden Bereichs rausfinden muss. Interessant auch die Frage, wie sich das bei REC verhält.

**Comment by mespotine** [comment]
Ist so knifflig alles nicht. Hatte mir da mal ne Prototyp-Variante zum Testen meiner Api gebaut. Die hab ich bestimmt sogar noch irgendwo.

Was eher ein Problem ist, dass man nicht 100% perfekt weiterlaufen lassen kann, es kommt immer zu einem Knackser. Evtl ists also sinnvoll dann noch eine Sekunde "zurückzuspringen", um nochmal ab kurz davor reinzuhören, sonst könnte der Knackser einen daran hindern Knackser in der Aufnahme zu hören.

Das Thema REC klingt interessant, denn ich kann mir eigentlich nicht vorstellen, dass RippleCut während der Aufnahme überhaupt interessant ist...

**Comment by fernsehmuell** [comment]
Im Stop-Modus sollte der Cursor nach dem Ripple Cut zur Schnittstelle springen, sonst landet man (ich) oft in unbekannten Bereichen der Timeline und ist verwirrt.
