### ISSUE TITLE
Ultraschall-Docs als Hilfe-Menü hinzufügen 

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#133]
Dazu muss man nur die PDFs(andere Formate gehen nicht) ins Verzeichnis Docs im Ressourcenverzeichnis packen, dann erscheinen sie sofort im Menü 

Help->Documentation->

**Comment by mespotine** [comment]
@rstockm Hab Dich mal damit assigned, weil Du die PDFs, Keymap,etc eh nochmal am Wickel haben wirst.

**Comment by rstockm** [comment]
Interessant. Ist leider dann recht tief versteckt, und man kann dieses Menü (im Gegensatz zu allen anderen) auch nicht modifizieren. Mal überlegen, ob außer der Keymap da noch etwas anderes als PDF Sinn macht.

**Comment by rstockm** [comment]
Ist in https://github.com/Ultraschall/ultraschall-portable/commit/a2b57a23f0c6be514913aee7a0ad9072cbe34218 umgesetzt. Muss aktualisiert werden, dazu vielleicht das Changelog.

**Comment by mespotine** [comment]
Changelog wäre super. Einziges Problem ist, dass wie nur PDFs verlinken können und Erklärbär-gifs in PDFs nicht funzen, soweit ich weiß.

**Comment by rstockm** [comment]
Hm leider kann man das Help Menü selbst nicht frei editieren.
Ich überlege, noch entsprechende Ordner im Podcast-Menü anzulegen mit Hilfe-Targets

**Comment by mespotine** [comment]
Wird anderweitig gelöst durch Hilfebuttons in den entsprechenden Dialogen mit Links auf die Online-Docs des Dokuteams.
