### ISSUE TITLE
Verschieben von Items über Tastatur mit Beschleuningungsfeature

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#14]
Wenn man das Verschieben von Items über Tastatur macht, so geht das nur in relativ kleinen Schritten.
Was wir stattdessen machen sollten: Wenn man Alt+links oder Alt+rechts gedrückt hält, so sollten die Schritte sich suksessive vergrößern, um das Verschieben in größeren Projektteilen möglich zu machen.
Speziell in langen Projekten verschiebt man sich sonst dumm und dusselig ;)

Der Beschleunigungsfaktor sollte sich auch nach Projektlänge richten...

**Comment by fernsehmuell** [comment]
Dazu eine Idee:
Das Script schreibt nach dem verschieben einen genauen Zeitstempel + aktuellem Beschleunigungswert in den Key Value Store. Beim starten guckt es nach, ob im Store was aktuelles steht und reagiert entsprechend.

Spricht irgendwas gegen den KV Store?

**Comment by rstockm** [comment]
Finde ich gut.

**Comment by rstockm** [comment]
Ist aufgegangen in

https://github.com/Ultraschall/ultraschall-portable/pull/73
