### ISSUE TITLE
Automatisches Speichern aktivieren

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#140]
In den Settings wird ein vernünftiges Verfahren für automatisches Speichern der Projektdatei alle x Minuten eingestellt.

**Comment by rstockm** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/3195116/64741724-ce06ad00-d4f9-11e9-9cf9-b0722a21a5e0.png">

**Comment by rstockm** [comment]
Zu überlegen, ob man viele timestamped Backups haben will und wo die landen.

**Comment by mespotine** [comment]
Wenn wir die Checkbox "Save to timestamped file in project directory" anwählen, dann im Projektverzeichnis.
![image](https://user-images.githubusercontent.com/4251851/79491031-1cdf6c80-801e-11ea-9a1b-fa740c4c520c.png)

Ich würde sagen, dass entweder alle 5 oder 10 Minuten gesichert wird, wobei wir das modifizieren können per Lua. Könnten wir also in den Settings eintragbar machen.

Ich setz auch mal das Milestone auf 4.0.1

**Comment by Feivel65** [comment]
Freu ich mich drauf! 

Habe selbst keine Option in den Standard-Einstellungen gefunden, aber ließen sich die `.RPP-BAK`'s in einen Unterordner des Projektverzeichnisses legen? Die zentralisierte Option aus den Reaper-Settings find' ich eher müßig.

**Comment by mespotine** [comment]
Geht leider nicht, nur im Projektverzeichnis oder in einem zentralisierten.
Es wäre möglich das im Hintergrund zu verschieben, aber ich glaub nicht, dass Reaper dann noch alle Dateien findet, wenn Du versuchst die Projekte zu öffnen.

**Comment by rstockm** [comment]
Ja dann kommt der gefürchtete "offline Media" Dialog und den zu erklären ist im Support wieder ziemlicher Aufwand.
Ich sehe aber natürlich auch den Punkt, dass das Projektverzeichnis schnell voll werden kann bei längeren Projekten.
Wenn man aber den Minutenwert "vor außen" lesen/schreiben kann (bald per API), geht dass dann nicht auch mit dem Pfad darunter? Dann könnten wir den dynamisch anpassen vor der Aufnahme:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/3195116/92671782-758a0b80-f317-11ea-9a56-a3b0dd68307a.png">

**Comment by rstockm** [comment]
Hier wird so was auch schon lange gefordert und X-Raym hat ein Skript gebaut das aber leider nicht mehr online ist:

https://forum.cockos.com/showthread.php?t=199379&highlight=autosave+subfolder&page=2

**Comment by rstockm** [comment]
Gelöst mit

https://github.com/Ultraschall/ultraschall-portable/commit/677c5bd6852994e2975e855a398cd03ececd76b6

Ist jetzt auf 10 Minuten gestellt.
