### ISSUE TITLE
Plausibilitätschecks für Recording

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#147]
Wenn man aufnimmt und dabei die Playrate noch auf falsche Geschwindigkeit eingestellt hat, dann kann das zu allerlei Problemen führen.
Daher sollten wir bei Recording nen Plausibilitätscheck einbauen der warnt oder sogar automatisch die Playrate auf 1.0 zurücksetzen(eventuell mit dem Eventmanager?)

**Comment by rstockm** [comment]
Ist aufgegangen im Soundcheck:

https://github.com/Ultraschall/ultraschall-portable/commit/2e8baad27c834aee1ea2af3d62adef381e6efaa6
