### ISSUE TITLE
Shortcut für rename Take

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#15]
Da wir den Doppelklick auf Items zum öffnen der item properties verändert haben, sollte es einen schnellen Weg geben um ein ausgewähltes Item umzubenennen.
Verschiedene Lösungsansätze:
- Nutzung der Action "rename take..." (_XENAKIOS_RENMTAKE)
- Nutzung der item properties

entweder/und über

`alt`+`Klick` auf ein item oder
über einen Shortcut, Vorschlag `alt`+`n`

Meinungen?

**Comment by fernsehmuell** [comment]
Mouse modifier halte für nicht so gut, da man schon mit Rechtsklick+Menüpunkt auswählen in die item properties kommt. Wir könnten aber die Tastenkombination für Source Properties nehmen, die braucht niemand. -> CMD+F2

**Comment by rstockm** [comment]
F-Tasten finde ich für Shortcuts wiederum eher so meh (auch wenn wir schonneinige haben): auf MacBooks wissen 80 Prozent der Leute nicht wie man da ran kommt weil man zusätzlich noch einen modifier-Key drücken muss...

**Comment by mespotine** [comment]
Was würde denn gegen das hier sprechen, was ich mal ins Sendegate reingepackt hatte?

https://sendegate.de/t/release-ultraschall-3-1/6633/59?u=mespotine

Das würde 100% aller UseCases erschlagen, für die man in die Item Properties muss, ohne zusätzliche Shortcuts oder Mouse-Modifier, also auch das Umbenennen von Takes...

**Comment by rstockm** [comment]
Nein, hässliche GUI, wollen wir nicht :-)

**Comment by fernsehmuell** [comment]
Dann vielleicht einfach "N" wie Name. Das Nudge-Setting kann auch auf ALT+"N"

**Comment by mespotine** [comment]
Wäre das nicht gut passend im MediaItem -Contextmenü?

**Comment by rstockm** [comment]
Umgesetzt in 

https://github.com/Ultraschall/ultraschall-portable/commit/3e61749c4bb9d33ece3d1f8eb0d3bb1280647e5e
