### ISSUE TITLE
Auto Follow Off ausschaltbar machen

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#159]
Nicht immer ist der Auto Follow Off hilfreich, manchmal ists einfach besser, wenn der Rechner einem nicht mit "Hilfen" in die Quere kommt und einem den Workflow auseinandernimmt.
Das passiert Einigen, die den Auto-Followmode-Aus nicht exakt in den Workflows verwenden, wie er gedacht ist.

Daher brauchen wir die Möglichkeit den FollowMode-Off auszuschalten in den Settings, so dass man Follow an/aus 100% manuell machen kann, wenn es für einem besser ist.

**Comment by rstockm** [comment]
Schlank implementiert dank US-Settings in:

https://github.com/Ultraschall/ultraschall-portable/commit/09ce467fb3c93e39396c6f013020cb4d1ee0850b
