### ISSUE TITLE
Label im Dialog MP3 Metadaten umbennen

### ISSUE THREAD

**Issue by heikopanjas** [Ultraschall/ultraschall-portable#167]
Einige Label für die Texteingabefelder im MP3-Metadatendialog haben keinen Bezug zum Podcastwesen. Deshalb bitte nach folgender Vorschrift umbennen:
`Title` -> `Episode`
`Artist` -> `Author`
`Year` -> *entfällt*
`Genre` -> `Category`

**Comment by mespotine** [comment]
Kann ich ändern, aber Jahr würd ich gern drin behalten. Ich nutze das sehr häufig.

**Comment by heikopanjas** [comment]
Echt? Genau das Jahr? Wofür denn?

**Comment by rstockm** [comment]
Um die Verständlichkeit weiter zu erhöhen, würde ich vorschlagen:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/3195116/71314888-8e812280-2451-11ea-9856-4dd7fbfa9055.png">

?

**Comment by heikopanjas** [comment]
Von mir aus genehmigt. Bleibt noch die Frage wegen des `Jahr`es.

**Comment by rstockm** [comment]
Ah, oben gesehen. Frage ist ja: schreibst du das Jahr in die MP3 oder nein? Wenn ja, sollten wir es auch drin lassen im Formular.

**Comment by heikopanjas** [comment]
Ich schreibe das jetzt rein, sehe aber nicht warum der User das eingeben sollte.

**Comment by mespotine** [comment]
Ah, ich versteh was Du meinst, dass wir einfach das Jahr automatisch eintragen anstatt dem User das aufzubürden. 
Da wär ich ja eher dafür per Default da das aktuelle Jahr im Dialog schon einzutragen und wers ändern will, soll es tun.

**Comment by heikopanjas** [comment]
Oder so.

**Comment by mespotine** [comment]
Wird gelöst durch #120
