### ISSUE TITLE
Actions für vor/zurück-Springen von Schnitt zu Schnitt

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#17]
Wenn man einen Podcast geschnitten hat, möchte man evtl nochmal die Schnitte prüfen, ob auch alles im Lot ist.
Dafür muss man bisher ziemlich umständlich klicken und scrollen und das ist lästig.

Was wir also brauchen: Actions, mit denen man den nächsten/vorherigen Schnitt schnell anspringen kann.
Wenn man Tracks selected hat, dann springt man nur die Schnitte in diesen Track(s) an, ansonsten alle Schnitte, die im Projekt existieren.

Das dürfte, zusätzlich zum Springen von Marker zu Marker, eine sehr praktische Funktion sein...

(Hab ich schon fertig gebaut ;) )

Würd ich dann auf die Shortcuts Cmd+Alt+links und Cmd+Alt+packen

**Comment by mespotine** [comment]
Mal kurz hier reingepackt, bis ich das Git-Thema gut genug verstanden habe um es einzupflegen...

[ultraschall_jump_left_to_itemedge-skripte.zip](https://github.com/Ultraschall/ultraschall-portable/files/1779057/ultraschall_jump_left_to_itemedge-skripte.zip)

**Comment by rstockm** [comment]
Was unterscheidet das von der bestehenden Action `alt`+`pfeilrauf/runter`?

**Comment by mespotine** [comment]
Habs mal getestet. An sich kaum was, aber es gäbe uns die Möglichkeit Einiges noch zu individualisieren.

Mein Skript kann z.B. auch Marker, Regions anspringen, was wir optional auswählbar machen könnten. 
Darüber hinaus nervt mich extrem, das Verhalten bei Crossfades, also wenn ein Item in eine Anderes übergeht. Dann springt er immer den Anfang und das Ende des Crossfades an, obwohl meines Erachtens da nur der Anfang eines Crossfades im Normalfall interessant ist. Dadurch haben wir unnötige Aktionen, die für 90% aller Podcastenden da draußen keinen Sinn ergeben(spontan aus dem Bauch heraus gesagt).
Ich würd also noch ergänzen wollen, dass man nur den Anfang von Crossfades anspringt, was per ultraschall.ini(und in nem späteren US-Settings-Manager) ausgeschaltet werden kann.

Was wir auf jeden Fall aber machen sollten, wäre Edit-Marker auch mit anspringen. Da das springe von Item-Edge zu Item-Edge hauptsächlich zum Testen und navigieren von Schnitten da ist, wäre das sinnvoll, da ein Edit-Marker ja auch ein Schnitt ist, der noch nicht gemacht wurde.
So stolpert man, wenn man am Ende nochmal alle Schnitte zum Testhören durchskipped, definitv auch über Edit-Marker, die Schnitte markieren, die man verpeilt hat zu machen und kann das noch nachholen...

**Comment by rstockm** [comment]
Ok, überzeugt, finde ich sinnvoll. Die Action würde dann also "alle sinnvollen Elemente" anspringen. Ich würde dann dazu neigen, die auf den bisherigen Shortcut zu legen, oder aber wir überlegen die Belegung der Pfeiltasten generell nochmal neu...

**Comment by mespotine** [comment]
Ich wär auf jeden Fall dafür, wenn wir Alt+Pfeiltaste für sowohl Sprung von Schnitt zu Schnitt/sinnvollen Elementen als auch für Vor und Zurück definierte Sekunden belegen. Die beiden Shortcuts liegen von der Sinnhaftigkeit sehr nahe beieinander, speziell, wenn man Schnitte mehrfach abhören will...

Also quasi Alt+Rauf/Runter - spring zu sinnvolles Element, Alt+Links/Rechts - spring um vordefinierte Sekunden.

Ich hab mir noch nicht das JKL-System von @fernsehmuell angeschaut, aber vielleicht können wir das ja ineinander integrieren... und so #18 mitfixen...

**Comment by rstockm** [comment]
Ich überlege, ob es nicht sogar sinnvoller wäre unsere neue "spring das nächste sinnvolle Element rechts/links an" Funktion nicht auch besser auf Pfeil links/rechts aufgehoben wäre, anstatt oben unten? etwa mit `alt` - das nudge was dort gerade liegt wird doch eher selten benutzt.

**Comment by mespotine** [comment]
Witzig, genau darauf hatte ich mir meine Prototypen-Variante auch gelegt gehabt ;)

Wär ich für...

**Comment by rstockm** [comment]
Nudge könnte man dann auf `alt`+`cmd` rechts/links verschieben.

**Comment by lootsy** [comment]
> neue "spring das nächste sinnvolle Element rechts/links an" Funktion nicht auch besser auf Pfeil links/rechts aufgehoben wäre

Ich (als (Noch-)Nicht-US-Nutzer) habe mich gefragt, warum sie da nicht schon liegt...

**Comment by mespotine** [comment]
Erledigt
