### ISSUE TITLE
Jog Shuttle - Shortcuts für Vor und Zurückspringen um konfigurierte Sekunden

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#18]
In Kombination mit den von mir vorgeschlagenen Shortcuts für
[Issue 17 - Actions für vor/zurück-Springen von Schnitt zu Schnitt](https://github.com/Ultraschall/ultraschall-portable/issues/17) 
macht es auch Sinn die Tastenkombination Cmd+Alt+Rauf und Cmd+Alt+Runter mit den Actions:

"Xenakios/SWS: Move cursor right configured seconds"

und 

"Xenakios/SWS: Move cursor left configured seconds"

zu belegen. 
Wenn man also einen Schnitt angesprungen hat, kann man so schnell vor/zurück springen, um einen Schnitt nochmal abzuhören, ohne dafür erst lästig mit Maus hantieren zu müssen oder ewig auf die Pfeiltasten links und rechts drücken zu müssen.

**Comment by rstockm** [comment]
Gegenvorschlag: dafür baut man (endlich) mal die Jog-Shuttle Funktion von @fernsehmuell ein?

**Comment by mespotine** [comment]
Sind das die legendären JKL-Skripte?

**Comment by fernsehmuell** [comment]
Ich habe den Branch  JOG-SHUTTLE-#18 dazu angelegt. Sind derzeit die aktuellen Shuttle Script aus meinem AvidMediaComposerStyle Repos.

Benutzung:
J K L Tasten mappen auf das passende Script. Buchstabe in () des Scriptnamens.
J= bewege Cursor Rückwärts
K=Pause
L= Play
bei mehrmaligem Drücken erhöht sich die Geschwindigkeit um jeweils eine Stufe.
Da es in Reaper keinen negative Wiedergabegeschwindigkeit gibt, musste ich da mit einem Backgroundscript arbeiten und es gibt auch keinen Ton.

**Comment by rstockm** [comment]
@fernsehmüll da scheint mir noch ein Issue zu zu fehlen? Kein Feature-Branch ohne Issue und Projektkarte.

**Comment by rstockm** [comment]
Ok, das scheint soweit zu funktionieren. Was ich noch nicht so ganz sehe ist: wofür braucht man Pause und Play, wenn beides auch die `return` Taste erledigt? Wäre dann nicht eine Taste weiter rechts anstatt von `j` zusammen mit der `return` Taste sinnvoller?

**Comment by fernsehmuell** [comment]
Das hat sich scheinbar so eingebürgert J links K Mitte L Rechts wie früher diese Shuttleräder.
Öh ist das nicht das Issue hier?

**Comment by rstockm** [comment]
Ok, jetzt habe ich das verstanden: `L`macht auch eine Beschleunigung, sehr schön. Frage: es gibt jetzt 4(?) Geschwindigkeiten: da würde ich gerne noch mehr sehen, sprich dass man die Geschwindigkeit in beide Richtungen noch weiter steigern kann. Möglich?

Dann: der Branch enthält jetzt Code, der nicht so ganz US Standard ist - unsere helpers.lua wird nicht genutzt etc. - ist auch klar, da das separate Skripte waren. Vorschlag: Branch zurücksetzen oder gleich schließen und einen neuen aufsetzen, und das nochmal sauber implementieren? Also auch Referenzen raus auf "Fernsehmüll", unsere reaper.ini als KV-Store etc.

Dann finde ich das aber jetzt - wo ich's mal verstanden habe - so wertvoll, dass es auch regulär auf `JKL` landen wird.

**Comment by fernsehmuell** [comment]
Ich mache einen komplett neuen Branch und mache alles neu, das ist am saubersten. Mit den Geschwindigkeiten gucke ich mal ich glaube da war oben irgendwo eine Grenze, wenn man die Reaper Playbackrate nimmt. Man könnte natürlich für größere Geschwindigkeiten auch das Backgroundscript nehmen.
