### ISSUE TITLE
Neuer Export-Assistant 

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#199]
Der derzeitige Export-Assistant ist relativ unterentwickelt. Das führt dazu, dass einige Export-related Sachen etwas verstreut sind oder gar ins derzeitige UI-Konzept nicht einbaubar sind.

Daher ists Ziel für die 4.1er eine komplette neue Version des ExportAssistants zu bauen.

MainFeatures:
Der komplette Exportworkflow ist in einzelne Schritte aufgeteilt, die in einzelnen Tabs abgebildet werden.
Folgende Schritte wären denkbar:
 - Rendering-Format(e) und Zielordner fürs Rendering
 - allgemeine Metadataeingabe (Title, Podcast, Genre, etc) + Cover(mit rudimentärem Cover-Editor)
 - Kapitelmarkenmanagement
 - Shownote-Management
 - Transkiptionsmanagement
 - Export nach Auphonic/Podigee
 - Podcast-Blogpost schreiben(mit rudimentärem Support für Formatierung) sowohl fyyd, Podlove als auch Podigee
 - Ein Tab auf dem es nur einen Button gibt: "Mach!"

Weiteres was es haben sollte:
- Presets für verschiedene Podcasts, so dass man sich die ganzen Sachen vorausfüllen kann für einen bestimmten Podcast, und man nicht alles neu eingeben muss.

Falls Ihr noch weitere Ideen habt: immer hier rein damit.

**Comment by derphilipp** [comment]
Zusätzliche Ideen: 
* Audio-Processing via Auphonic Multitrack offline einbauen; Dann könnte ich meinen Workflow auch lokal laufen lassen.
* Beliebige Kommandos per Skripting ausführen lassen (dann wäre z.B. Upload möglich)

**Comment by mespotine** [comment]
Du meinst per Shell-Skripte oder Lua oder so?

**Comment by derphilipp** [comment]
Ich meinte Shell-Skripte;
