### ISSUE TITLE
First Start: Setzen einer sinnvollen Fenstergröße

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#2]
Um das Onboarding zu verbessern, sollten wir beim allerersten Start - und nur dann, da haben wir schon eine Condition für - prüfen welche Auflösung der Screen hat und irgendwie(tm) das Reaperfenster entsprechend auf eine sinnvolle Größe (80% des Viewports auf einem Monitor?) setzen.

**Comment by mespotine** [comment]
Ich hab noch nicht ganz verstanden, was der Mehrwert dessen ist...

**Comment by rstockm** [comment]
Ein oft auftretendes Problem ist, dass das Soundboard in einem zu kleinen FX Fenster gestartet wird und dann der zentrale „Open Folder“ Button nicht sichtbar ist. Das würde durch ein ausreichend großes REAPER-Fenster vielleicht gelöst.
Alternative Strategien sind gern gesehen...

**Comment by mespotine** [comment]
Wird das jetzt lösbar durch die neue Soundboard-Version oder brauchen wir da ne Reaper-Fenster-setz-Funktion in der Api?
