### ISSUE TITLE
Exklusives auswählen eines von mehreren ausgewählten Items geht nicht

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#20]
_EDIT (lootsy)_

### Das ist SOLL:
* Standardverhalten von Reaper (und jeder PC-Anwendung)
    * wenn man mehrere Items ausgewählt hat und dann nur eines der ausgewählten anklickt, wird die Auswahl so geändert, dass nur noch dieses eine ausgewählt ist bzw. wird.
* wenn man es anklickt mit CMD/Ctrl (Shift?) soll die Mehrfach-Auswahl erhalten bleiben

### Das ist (leider) IST:
Dies ist ein Regressions-Bug! Dieses (normale) Verhalten existierte in US vor der Version 3.1.
In der 3.1er ist diese gewünschte Verhalten bei der Auswahl von Items leider weggefallen. :-(

**Comment by mespotine** [comment]
Fix temporär hier reingepackt, bis ichs ins Repo eingepflegt bekomme....

[Doubleclick-Arrange-and-Exclusive-item-selection.zip](https://github.com/Ultraschall/ultraschall-portable/files/1779101/Doubleclick-Arrange-and-Exclusive-item-selection.zip)

**Comment by lootsy** [comment]
Ok, da ist noch einiges an Umgang mit git zu tun/erlernen/machen/usw usf.
Ich versuch mich mal an nem Diff.

**Comment by rstockm** [comment]
Ok, jetzt habe ich das endlich mal verstanden. Ja, kann ich reproduzieren, macht Sinn.

**Comment by lootsy** [comment]
Hi @mespotine,

ich kann das auch einpflegen, verstehe die reaper-kb.ini (noch) nicht.
Kann deine Zeile als letzte der ACT Zeilen hinzugefügt werden? Oder muss man bei den ACT Zeilen eine bestimmte Reihenfolge einhalten?
Muss
Ist z. B. in einer ACT Zeile der Gebrauch eines "eigenen US-Befehls" nur dann gestattet, wenn er __vorher__ in der kb.ini definiert wurde?

Wo kann ich mehr über die kb.ini lesen / erfahren / mich einlesen? Offizielle Doku / eigene Doku?

**Comment by mespotine** [comment]
Ich hab noch ne verbesserte kb-ini Doku in Arbeit. Ich pack die mal heute irgendwo noch hoch, auch wenn die nicht 100% fertig ist...

**Comment by mespotine** [comment]
Verbesserte kb.ini-Doku. Es fehlen aber noch die Shortcuts, die Reaper per default vergibt, es gibt aber ne Beschreibung, wie man an die rankommt...

http://mespotine.de/Ultraschall/reaper-kb.ini.html

**Comment by rstockm** [comment]
Umgesetzt und im master.
