### ISSUE TITLE
[BUG] "Finished rendering" notification *extremely* loud

### ISSUE THREAD

**Issue by derphilipp** [Ultraschall/ultraschall-portable#200]
**What were you doing?**
Rendering any project

1. Open project
2. Render project
3. Wait for rendering to finish

**What did you expect to happen?**
No sound, or sound at reasonable volume

**What happened instead?**
An extremely loud chapter-mark style sound is piercing my eardrums

**Version of Ultraschall**
4b3 Catalina

**Operating system and language running Ultraschall**

macOS 10.15.3

**REAPER version running Ultraschall**

v6.03/64 rev 881187 (Jan 13 2020)

**Audio interface model and used firmware incl. version**

Zoom H6

**Screenshot(s)/video(s) showing the problem:**
-

**Comment by mespotine** [comment]
Ich kanns nicht reproduzieren, passiert das immer noch bei Dir, @derphilipp ?

**Comment by mespotine** [comment]
Ich kanns nicht reproduzieren, passiert das immer noch bei Dir, @derphilipp ?

**Comment by derphilipp** [comment]
Schon lange nicht mehr passiert - habe aber auch lange nicht mit Kopfhörer geschnitten und gerendert 🤷

**Comment by mespotine** [comment]
Schließ ich mal. Sollte es wieder auftreten, kanns ja wieder geöffnet werden.
