### ISSUE TITLE
[BUG] Switching between Projects plays Chaptermark-Sound

### ISSUE THREAD

**Issue by derphilipp** [Ultraschall/ultraschall-portable#201]
**What were you doing?**

1. Have multiple Projects open, using Tabs
2. Play project
3. Switch from non-playing Project back to Project

**What did you expect to happen?**
Nothing

**What happened instead?**
A "chaptermark"-style sound was played

**Version of Ultraschall**

4b3 Catalina

**Operating system and language running Ultraschall**

macOS 10.15.3

**REAPER version running Ultraschall**

v6.03/64 rev 881187 (Jan 13 2020)

**Audio interface model and used firmware incl. version**

Zoom H6

**Screenshot(s)/video(s) showing the problem:**
-

**Comment by mespotine** [comment]
gelöst durch #428
