### ISSUE TITLE
Stelle eine brauchbare gitignore zur Verfügung.

### ISSUE THREAD

**Issue by lootsy** [Ultraschall/ultraschall-portable#21]
Aktuell werden beim Start von Reaper in dem "ultraschall-portable" Verzeichnis (vgl. Ralfs Video) diverse ini Dateien manipuliert.
Dadurch bemerkt git natürlich Änderungen, die gestaged / commitet werden wollen. Damit das nicht passiert und nicht jedesmal wieder neu Hand anlegen muss, soll es eine erste Version einer "sinnvollen" gitignore geben.

**Comment by lootsy** [comment]
Können alle ini Dateien außer "reaper" und "ultraschall" in die gitignore?
![geänderte ini Dateien](https://user-images.githubusercontent.com/21980459/37133622-40cac7b0-229d-11e8-983b-d659ae4f25e9.png)
Das ist übrigens ein Screenshot aus [VS Code](https://code.visualstudio.com/), meinem ~~neuen~~  Lieblingseditor!

**Comment by mespotine** [comment]
Die inis dürfen nicht ins gitignore, beziehungsweise nur einige Ausgewählte.
Welche das aber konkret sind, wird erst Gegenstand der 4.0er sein, da wir dafür noch reichlich Forschungsarbeit managen müssen, denn viele Settings werden in diverse dieser .inis verteilt eingetragen und wir wissen noch zu wenig, in welchen für uns relevante Settings drin sind und in welchen nicht.

Das wird also wohl erst mal so bleiben müssen, bis wir uns das Thema genauer angeschaut haben, aber wie gesagt, erst zur 4.0er...

**Comment by rstockm** [comment]
Na ein paar kann man da schon noch aussieben, ich mache mal einen Aufschlag.

**Comment by rstockm** [comment]
Das hier hilft schon mal weiter:
https://github.com/Ultraschall/ultraschall-portable/compare/US311-21-stelle-eine-brauchbare-gitignore-zur-verfuegung-%2321

Wir(tm) sollten unbedingt mal die S&M.ini aufräumen: da wimmelt es nur so von Altlasten. Alles mit "Wikigeeks" etwa. Schadet nicht, kann aber auch keiner was mit anfangen. Das Verfahren wäre: mit der Version diffen, die eine cleane SWS Installation mitbringt, und dann nur die Einträge rauswerfen die Pfade etc. enthalten, andere Einstellungen will man beibehalten.

Mache ich nachher mal.

**Comment by rstockm** [comment]
So, bin durch die S&M.ini durch. Was mir gar nicht gefällt sind die immer noch verbleibenden Pfadangaben: die bekommt man glaube ich aber auch nicht sinnvoll weg. Da sie bisher aber auch nie wen gestört haben, ist es vermutlich auch wumpe. Im würde auf jeden Fall nicht riskieren wollen in die entsprechenden Einträge einfach "" einzuschreiben.

**Comment by lootsy** [comment]
Anregungen für eine gitignore kann man z.B. von hier (https://github.com/Windower/Lua/blob/dev/.gitignore) nehmen. 
Da ist natürlich viel Windows Kram drin. (aber auch nur der interessiert mich aktuell ;-)

**Comment by rstockm** [comment]
Gelöst mit:
https://github.com/Ultraschall/ultraschall-portable/pull/22

**Comment by lootsy** [comment]
Nun ja, "gelöst"... ;-)

In dem PR #22 sind jetzt zwei Dinge vermischt.
1. ini-Dateien aufräumen / säubern / "CleanUp"
2. ini-Dateien der gitignore hinzufügen.

Dieses Issue war ja eigentlich für letzteres gedacht. Ich glaube, dass es sehr hilfreich ist, wenn wir versuchen in Zukunft verstärkt darauf zu achten, dass in einem Issue / PR auch _nur das_ gemacht wird, was der Issue-Titel nahe legt.
Das macht es vor allen Dingen fürs Reviewen / Testen viel einfacher. Und man verzettelt sich nicht so.
Für das Aufräumen hätte ich n eigenes Issue gemacht.
My 2 ct.

**Comment by rstockm** [comment]
Ja. Da wir aber im Moment eine Durchlaufzeit von einem Pull-Request pro Quartal haben, würde ich diese total egalen Tickets gerne mal zügig abräumen, damit man anfangen kann zu arbeiten. Ja, das hätten wir alles vor dem ursprünglichen Commit machen können, iss aber nicht. My 2 Cent.

**Comment by lootsy** [comment]
done by 31426a8
