### ISSUE TITLE
[BUG] Ultraschall Soundcheck reports "samplerate" if audio interface settings are opened

### ISSUE THREAD

**Issue by derphilipp** [Ultraschall/ultraschall-portable#210]
**What were you doing?**

0. Use Windows 10
1. Use Ultraschall 4b3 on Windows 10 (exclusive audio mode, so we can change the audio interface settings)
2. Have all checks green (audiodevice set to 48KHz, etc.)
3. Have Ultraschall Soundcheck open
4. Open audio device settings of Reaper

**What did you expect to happen?**
Status to be "OK" or "unknown"
**What happened instead?**
Status of 48KHz Samplerate check was set to red/Error
**Version of Ultraschall**

**Operating system and language running Ultraschall**
Windows 10

**REAPER version running Ultraschall**

**Audio interface model and used firmware incl. version**
Rode Podcaster (USB)

**Screenshot(s)/video(s) showing the problem:**

**Comment by mespotine** [comment]
Das scheint nicht mehr der Fall zu sein, daher schließ ich das mal. Sollte es trotzdem noch sein, einfach bitte wieder aufmachen, @derphilipp .
