### ISSUE TITLE
Win: Pfadangaben sollen per Variable anzupassen sein

### ISSUE THREAD

**Issue by lootsy** [Ultraschall/ultraschall-portable#23]
Pfadangaben in ini-Dateien sollen (für die Windows-Varainte) nicht hart kodiert sein, sondern über (System-)Variablen anpassbar sein.

vgl. c55009d und [Kommentar dazu](https://github.com/Ultraschall/ultraschall-portable/pull/22#commitcomment-28006083)

**Comment by rstockm** [comment]
Das wäre natürlich genauso für die Mac Variante sinnvoll, da stehen überall in den Pfaden meine Verzeichnisse drin... aber keine Ahnung ob/wie das geht.

**Comment by lootsy** [comment]
Gehen tut das sicherlich, aber meine Mac-Zeiten hörten bei System 7.5.3 und dem [Performa 630](https://computermuseum.wordpress.com/2011/01/03/performa-630-dos-compatible/) auf. ;)
Also keine Ahnung...

**Comment by mespotine** [comment]
Wird spätestens dann knifflig, wenn jemand mit ner portablen Version arbeitet, die auf nem USB-Stick packt und woanders ausführt, wo die System-Variablen-Pfade nicht gesetzt sind.
Wenn wir dafür nen Workaround finden, wär ich aber voll dafür. Gäbe einige Pfade, die ich so gern sauber gesetzt sehen wollen würde.
Würde auch in Skripten ne Menge Aufräumen ermöglichen...

**Comment by pthoelken** [comment]
Man könnte vor jedem Startup prüfen ob die System variablen vorhanden sind; wenn nicht, diese Anlegen lassen. Würde dann halt nur ein UAC aufploppen lassen

Könnte man als "Portable Initialisierung First Startup" laufen lassen.

**Comment by mespotine** [comment]
Da das Ganze wohl kaum machbar ist(nach derzeitigem Forschungsstand), schließe ich das Issue erstmal um aufzuräumen. Falls jemand aber noch ne Idee hat, wie man das Ganze gut und stable umsetzen kann, gern wieder öffnen.

**Comment by pthoelken** [comment]
Mal rein aus Neugierde gefragt: Wo ist denn das Problem, dass beim Startup-Loading mit abzufragen? Ich meine, ich habe mir den Code (noch) nicht angeschaut, aber für "unmöglich" halte ich es eigentlich in keiner Sprache.

**Comment by mespotine** [comment]
In der Hauptsache Reaper beizubringen diese Variablen zu nutzen. Das erfordert intensive Recherche und herumexperimentieren mit den Konfigurationsdateien, hauptsächlich reaper.ini
Wenn wir das Reaper beibringen können und das ohne Probleme funktioniert, dann ist das weniger ein Problem.

Achja, und wir müssen die Pfadangaben setzen bevor Reaper gestartet wird, sonst findet es eventuell nicht mal die eigenen Skripte oder das Theme oder irgendwas von uns.

Aber das muss mal jemand erforschen und ist nicht trivial. Braucht halt Zeit, die grad niemand hat.

Es gibt in der reaper.ini beispielsweise einen Eintrag lastcwd, in dem das letzte Arbeitsverzeichnis gespeichert ist.
Das wird von Reaper manchmal genutzt, manchmal ignoriert.
Allein das müsste schon dokumentiert werden wann das der Fall ist und wann nicht, eben weil davon abhängt, ob Reaper Sachen findet oder nicht.

Vermutlich machbar aber sehr zeitaufwändig und nach meiner derzeitigen Einschätzung mehr Arbeit und potenzielle Stolperfallen die uns Supportanfragen einbringen, als es praktischen Nutzen bringt.

Ich lass mich aber gern eines Besseren belehren.
