### ISSUE TITLE
Trackhöhe sollte sich automatisch anpassen, wie Hindenburg es tut.

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#235]
Für die 4.1 hätte ich gerne einen intelligenten Mechanismus, der die Höhe der Spuren optimiert. Unten immer ein wenig Platz, ansonsten aber alles gleichverteilt und die Höhe wächst/schrumpft mit Anzahl der Spuren. Hindenburg macht das gefühlt sehr gut.

**Comment by rstockm** [comment]
Ist mit der Beta 1 umgesetzt.
