### ISSUE TITLE
[BUG] Desktop-Link zum Theme verhindert u.U. Import des Themes

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#239]
Der Import des Themes funktioniert u.U. nicht, wenn man es mit Hilfe des Desktop-Links versucht zu importieren.
Stattdessen erscheinen Fehlermeldungen, "Can't create" für viele Files.

Ich vermute, dass das passiert bei Systemen, wo der Username einen Umlaut beinhaltet, wie äö oder ü.

**Comment by heikopanjas** [comment]
Ich denke das ist auf jeden Fall ein REAPER-Problem, das wir nicht fixen können. Wird also zur 4.0.1 nicht behoben werden. Zwei Möglichkeiten: 1) Wenn es schon ein Issue für den neuen Installer gibt, die Issue-Nummer von dem hier (239) per Label da dran kleben und auf wontfix stellen, oder 2) als Bug an Cockos melden und warten.

**Comment by heikopanjas** [comment]
Die Umlaute sind grundsätzlich nicht das Problem. Habe ich ausprobiert. Vielleicht könnte man nochmal gucken, wie die Varianz in der installierten Windows-Sprache auf den betroffenen Systemen ist, aber ich denke das ist Zeitverschendung. Die werden alle deutsch sein.

**Comment by heikopanjas** [comment]
Auf jeden Fall könnte man anhand dieses Bugs drüber nachdenken, ob man nicht einen Abschnitt `Known Issues` in das README oder CHANGELOG aufnimmt.
