### ISSUE TITLE
[ENHANCEMENT] Ducking beim Bauen

### ISSUE THREAD

**Issue by tomtjes** [Ultraschall/ultraschall-portable#245]
**Is your feature request related to a problem? Please describe.**
Beim Bauen von Beiträgen kommt es oft vor, dass man Musik unter Sprache ducken muss oder einen fremdsprachigen O-Ton unter der Übersetzung. Es ist anstrengend den Volume-Envelope dafür jedes Mal selbst zu bauen.

**Describe the solution you'd like**
Ich schlage vor, auf den Shortcut 'd' eine Funktion zu legen, die die ausgewählte Spur auf ein definiertes Level absenkt. Dies sollte in den Ultraschall-Settings definiert werden, am besten zusammen mit weiteren Parametern wie Länge und Position der Fades, ggf. auch Form der Fade-Kurven.

**Describe alternatives you've considered**
Es gibt ein funktionierendes Skript, vgl. https://sendegate.de/t/ducking-beim-bauen/5010 Mit den Ultraschall Settings gibt es jetzt die Möglichkeit, das Ganze in schön zu machen.

**Additional context**
Ich konnte keinen Branch finden, der für einen Pull Request geeignet wäre, daher siehe https://github.com/Ultraschall/ultraschall-portable/compare/master...tomtjes:ducking

**Comment by mespotine** [comment]
Ich hab mir das Skript mal angeschaut und verstehe nicht wirklich, was es tun soll. Auch kommt eine Fehlermeldung, wenn man die Volume-Automationsspur einblendet. So ist es glaub ich nicht so wirklich zu verwenden.

Ich versuche das mal selbst neu zu bauen, auch mit einem etwas kürzerem Skript, weil das schon ein sinnvolles Feature wäre.

Ich würde es so bauen, dass man die Tracks auswählt, wo geduckt werden sollte, dann mit ner Time-Selection angibt, wo geduckt wird.
Ich denke ein Dialog, wo man eingeben kann, wieviele Sekunden man ducken will und wie leise wäre auch noch sinnvoll. Dieser sollte sich den zuletzt eingegebenen Wert merken, so, wenn man immer 3 Sekunden Fades hat, man einmal 3 Sekunden eintippt und danach nur noch auf Enter drücken muss.
Eine zweite Action, die ohne Dialog die zuletzt verwendeten Settings anwendet, wäre auch sinnvoll.

**Comment by mespotine** [comment]
Ich hab mir das Skript mal angeschaut und verstehe nicht wirklich, was es tun soll. Auch kommt eine Fehlermeldung, wenn man die Volume-Automationsspur einblendet. So ist es glaub ich nicht so wirklich zu verwenden.

Ich versuche das mal selbst neu zu bauen, auch mit einem etwas kürzerem Skript, weil das schon ein sinnvolles Feature wäre.

Ich würde es so bauen, dass man die Tracks auswählt, wo geduckt werden sollte, dann mit ner Time-Selection angibt, wo geduckt wird.
Ich denke ein Dialog, wo man eingeben kann, wieviele Sekunden man ducken will und wie leise wäre auch noch sinnvoll. Dieser sollte sich den zuletzt eingegebenen Wert merken, so, wenn man immer 3 Sekunden Fades hat, man einmal 3 Sekunden eintippt und danach nur noch auf Enter drücken muss.
Eine zweite Action, die ohne Dialog die zuletzt verwendeten Settings anwendet, wäre auch sinnvoll.

**Comment by mespotine** [comment]
gelöst durch #431
