### ISSUE TITLE
[BUG] Pfeiltasten rauf/runter zoomen nicht mehr

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#247]
Pfeiltasten rauf und runter zoomen nicht mehr. Die müssten wieder belegt werden.

**Comment by rstockm** [comment]
Zudem `alt`+Pfeiltasten rauf/runter vertical scrolling, parallel zu Trackpads und Maus.

**Comment by mespotine** [comment]
Wird gelöst durch #261 262
