### ISSUE TITLE
[ENHANCEMENT] Alt+Pfeiltasten rauf/runter scrollen den Arrangeview vertikal

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#248]
Alt+Pfeiltasten rauf/runter scrollen im Arrangeview vertikal

**Comment by rstockm** [comment]
Gelöst durch https://github.com/Ultraschall/ultraschall-portable/commit/c0afc731388fcb0e0efd2de680bb4a410ec77703
