### ISSUE TITLE
[ENHANCEMENT] Set next marker to planned stage ins Menü/in nen Shortcut

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#249]
Ultraschall_Set_Next_Marker_To_Planned ist seit 4.0 drin, aber weder auf einen Shortcut gesetzt, noch in nem Menü eingetragen.
Das sollten wir noch ändern, weil das Feature schon von Einigen gewünscht wurde aber es derzeit schwer zu nutzen ist.

**Comment by rstockm** [comment]
Gelöst durch https://github.com/Ultraschall/ultraschall-portable/commit/38268f5e9392e0152e994666a72c4ca37e8601a2
