### ISSUE TITLE
[BUG] Soundcheck: zu später Samplerate-Check

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#250]
Jedweder Samplerate-Check nach der Aufnahme ist überflüssig. Einfachster Weg: das `prepare all tracks...` Flag abfragen, falls niemandem was eleganteres einfällt.

**Comment by mespotine** [comment]
Ich würde das derzeit so lassen und lieber zur 4.1 nochmal angehen, wenn wir die Soundchecks auf projektbasiert umstellen. Dann können wir das gleich in fluffig machen.

**Comment by rstockm** [comment]
Gelöst mit https://github.com/Ultraschall/ultraschall-portable/commit/ffb18ac066025ef2346c5657e38da3f015c34456
