### ISSUE TITLE
[ENHANCEMENT] cmd + w zum Fenster schließen

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#258]
Prüfen, ob man den Shortcut cmd+w einfach für das Schließen unserer selbstgebauter Fenster (Soundcheck etc.) nutzen kann.

**Comment by mespotine** [comment]
Wenn wir schonmal dabei sind, bau ich noch alt+f4 auf Windows mit ein. Ist nur nen kleiner Fix an der Gui-Lib.

**Comment by mespotine** [comment]
Gelöst durch #260
