### ISSUE TITLE
[ENHANCEMENT] Performance Marker Dashboard

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#259]
In seiner jetzigen Struktur lässt sich das Marker Dashboard nicht sinnvoll tunen. Es könnte aber probiert werden, an sinnvollen Stellen noch ein refresh-Timeline einzufügen um die Fluppdizität zu erhöhen.

**Comment by mespotine** [comment]
Wird zu US6 neu implementiert mit neuem Marker-Manager unter zuhilfenahme von ReaGirl
