### ISSUE TITLE
[BUG] Error for muted tracks even if no tracks are muted

### ISSUE THREAD

**Issue by holgerkrupp** [Ultraschall/ultraschall-portable#263]
When exporting, a message pops up that there are muted tracks, eventhough no tracks are muted.

<img width="1068" alt="Screenshot 2020-03-27 at 09 39 13" src="https://user-images.githubusercontent.com/2877360/77737884-1f4a3a00-700f-11ea-83b7-56ad232da275.png">

**Comment by mespotine** [comment]
There is a muted one: the master track

**Comment by mespotine** [comment]
Vielleicht sollten wir als Zusatzmeldung noch "Mastertrack ist gemutet" reinbauen. Vielleicht geht das etwas unter, wenn man den Mastertrack nicht angezeigt hat.

**Comment by mespotine** [comment]
wird gelöst durch #425

**Comment by mespotine** [comment]
wird gelöst durch #425
