### ISSUE TITLE
[BUG]Check internal Mic.

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#273]
in der __startuo.lua ist der MacOS Check für das interne Mikrofon nicht 100% sicher. Bei Rechnern mit HDMI kommt eine falsche Antwort.

Eine sicherer Methode:
system_profiler SPAudioDataType -xml | grep -A 1 "Built-in Input" | tr -d "\t" | awk '{gsub("<[^>]*>", "")}1' | tr -d "\n"

Pullrequest folgt.

**Comment by rstockm** [comment]
Gelöst durch https://github.com/Ultraschall/ultraschall-portable/pull/274
