### ISSUE TITLE
Goto next marker Verhalten

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#276]
Die Action "Custom: ULTRASCHALL: Go to next marker/project end" verhält sich meiner Meinung nach falsch, wenn ein Marker hinter dem Projektende (letztes Item) liegt dann springt er nämlich  in der Zeit zurück statt stehen zu bleiben. Das ganze sollten wir eh mal in ein LUA Script umbauen mit richtigem Undo und Soße und mittelscharf und so.

**Comment by mespotine** [comment]
Ah, er springt immer hin und her zwischen ProjektEnde und Marker hinter Projektende.

Ich fix das mal.

**Comment by mespotine** [comment]
Ist nen Reaper-Bug, den ich mal gemeldet habe. Das könnten wir zwar auch selbst hacken, aber GetProjectLength liefert leider nicht das Ende des letzten Items und das zu kalkulieren bedeutet das Ende aller Items zu checken zu müssen. 
Das frisst unnötig Ressourcen und ist laggy, wenn Du mehrere tausend Items hast.

Daher würd ich erstmal auf nen Bugfix auf Reaper-Seite hoffen und mit dem Verhalten solang leben.

**Comment by mespotine** [comment]
gelöst durch #426

**Comment by mespotine** [comment]
gelöst durch #426

**Comment by mespotine** [comment]
gelöst durch #426
