### ISSUE TITLE
[BUG] Magic Routing-Buttons zeigen nicht immer sauber an, welches Routing im aktuellen Projekt gewählt wurde

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#278]
Wenn man mehrere Projekttabs offen hat oder ein altes Projekt schließt und ein neues öffnet,
dann kann es sein, dass die MagicRouting-Preset-Buttons nicht das Routing anzeigen, welches im Projekt gerade vorhanden ist.

Beispiel:
In Projekt 1 hab ich Recording
In Projekt 2 hab ich Pre-Show

Wenn ich Pre-Show im zweiten Projekt angeklickt habe und dann zum ersten Projekt wechsle, so ist noch immer der Button Pre-Show ausgewählt, obwohl in Projekt das Routing für Recording aktiv ist.

Das kann zu Verwirrungen führen, weil man denkt, man hätte das richtige Routing, hat es aber nicht.

Das Gleiche kann auch passieren, wenn man ein neues Projekt(-Template) lädt, so dass man immer erst das richtige Routing manuell anklicken muss, damit man sicher ist, es ist das Richtige.

Der derzeitige Ansatz erfordert, dass man pro Reaperstart nur mit einem Projekt hantiert, weil nach Neustart die Buttons auf nicht ausgewählt gesetzt werden.

Das können wir besser ;)

Eventueller Ansatz:
Ein weiteres Event im Eventmanager, welches immer checkt, ob das aktuell offene Projekt sich geändert hat. Wenn es sich geändert hat, dann liest der Event aus dem Projekt aus, welches Routing-Preset gewählt wurde und setzt den entsprechenden Button auf ausgewählt.
Das kann man vielleicht vereinfachen, indem man in ein ProjExtState reinschreibt, welches das zuletzt ausgewählte MagicRouting-Preset war.

Potenzielles Problem: Wenn der User/die Userin an der Routingmatrix rumändert, was für uns nicht so leicht herausfindbar ist ohne dabei zuviel Performance zu verlieren.
Da würde ich aber dazu tendieren, dass wir einfach sagen, der ausgewählte Button reflektiert, was als Letztes ausgewählt wurde. Wenn der User was dran ändert, dann weiß die Person normalerweise, was sie tut.

Bonus: Wenn Routing-Snapshots ausgewählt werden, werden die MagicRouting-Presetbuttons auf unausgewählt gesetzt.

**Comment by rstockm** [comment]
Betrifft eventuell auch den Status des Follow-Mode und des Mauszeiger-Selekt-Status.
