### ISSUE TITLE
[ENHANCEMENT] READ/WRITE Verhalten bei Unterbrechung der Aufnahme

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#288]
Verhalten der Mute-Spur: Wenn ich mit dem Record-Button eine Aufnahme unterbreche, dann wechselt der Modus automatisch von Write zu Trim/Read. Er sollte wieder zurückspringen zu “write” wenn ich erneute aufnehme oder seinen Status bis zum Prepare all tracks gar nicht ändern.

Wird wohl auf ein Soundcheck-Modul hinauslaufen.

**Comment by mespotine** [comment]
Wird eventuell schon gelöst durch #284 und #285
