### ISSUE TITLE
[ENHANCEMENT] Windows-Installer: Theme auf Desktop installieren

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#291]
Da es mit der Desktop-Verknüpfung zur ReaperConfigZip-Datei von Ultraschall häufiger Probleme beim Import gibt und vollkommen unklar ist, woher diese Probleme kommen(eventuell Umlaute im Usernamen?), sollten wir die ReaperConfigZip-Datei einfach direkt auf den Desktop installieren.

Dies scheint wohl ohne Probleme zu funktionieren und daher könnte das die Lösung für das Problem sein.

**Comment by heikopanjas** [comment]
Fixed with https://github.com/Ultraschall/ultraschall-installer/commit/b81563891b20a5df0ef18b1bc49773037a05fd19?diff=split
