### ISSUE TITLE
[ENHANCEMENT]Neue Action: "adjust zoom centered at edit cursor"

### ISSUE THREAD

**Issue by timpritlove** [Ultraschall/ultraschall-portable#292]
**Is your feature request related to a problem? Please describe.**

Es sollte möglich sein, einen Punkt in der Timeline mit dem Edit Cursor zu markieren und schnell von diesem Punkt aus rein- und rauszuzoomen. Damit das mit einem Mousewheel shortcut nutzbar ist, ist eine bidirektionale action ("adjust zoom") notwendig.

**Describe the solution you'd like**

Eine neue Action einrichten: "ULTRASCHALL: adjust zoom centered at edit cursor"

**Comment by rstockm** [comment]
Ist zunächst mal auf cmd + Trackpad-Pinch gemappt. Für Mausbediehnung muss man nochmal schauen.
