### ISSUE TITLE
Entfernen von Einträgen der Kontextmenüs die irrelevant für Podcasts sind.

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#31]
Wir sollten mal die Einträge in den Kontextmenüs durchgehen und aufräumen, denn es gibt etliche Einträge, die für Podcastproduktion eigentlich nicht relevant sind und die Menüs nur unsinnigerweise aufblähen.

Ein Beispiel ist das Arrange-Context-Menu, wo ich mal ein paar Einträge markiert habe, die überflüssig sind.

![temp](https://user-images.githubusercontent.com/4251851/37317194-afbc7820-2663-11e8-8e11-e660bec869df.png)

Das sollten wir aufräumen um das Onboarding zu erleichtern und die Leute nicht mit Optionen zu erschlagen.

Eventuell können wir die übrigen Einträge nach UseCase sortieren und mit Trennern voneinander trennen und ein Label jeweils als Erstes packen. So wie das ausgegraute Ultraschall-Label im Track-Context-Menu , nur halt eines für "Marker" und eines für etc, pp

**Comment by rstockm** [comment]
Ja, das ist so ein Punkt. Ich hatte in einer frühen Version von Ultraschall die Menüs schon einmal stärker abgespeckt, dann aber von Release zu Release wieder stärker hergestellt -da sich eben zeigte, dass man doch etliche Features auch für Podcasting brauchen kann. Es ergibt auch ein Paar Probleme beim Updaten von REAPER - wenn die neue Features in die Menüs 
Ackern, sehen wir die schlicht nicht.
Aber ja: generell finde ich das gut.

**Comment by mespotine** [comment]
In dem Zusammenhang könnten wir auch noch ins Kontextmenü vom leeren TrackControlPanel noch die Einträge Insert Studiolink-Spur und Insert Soundboard-Spur direkt eintragen.
Dass die nur im Unterpunkt für Tracktemplates zu finden sind, find ich etwas ungünstig...

Ja, das würde auch für die 4.0er Konfigerhaltung ne aufwändige Hackaktion werden, um das alles konsistent zu halten. Sollten wir auf jeden Fall mal etwas uns überlegen.

Deswegen auch die Idee mit den ausgegrauten Labels, an Hand derer wir besser sehen können, in welches "Untermenü"(hab grad da kein besseres Wort für) wir unsere neuen Einträge dann hinzufügen, ohne dass wir an den alten etwas ändern müssen, egal was man sich drauf eingestellt hat.

Sollten wir uns mal in aller Ruhe anschaun...
