### ISSUE TITLE
[ENHANCEMENT] Magic Routing - schnelleres Umschalten+potenziell Ergänzen von "User Routing Settings"

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#320]
Derzeit ist das Magic Routing zu langsam im Umschalten, und es gibt Aussetzer beim Wechsel, weil alle HWOuts neu gesetzt werden müssen.
Das geht schneller, indem nur geändert wird, was sich geändert hat, ohne dabei alles zu löschen und neu zu setzen, was bei sich eigentlich nicht ändernden HWOuts zu Aussetzern führt, die eigentlich unnötig sind.

Des weiteren ist es derzeit nicht möglich noch zusätzliche Routing-Einstellungen durch den User hinzuzufügen. Wenn also jemand noch weitere HWOuts zu diversen "Trackprofilen" hinzufügen will, geht das derzeit nicht.
Das sollte sich ändern, sprich: Magic Routing sollte mit "Trackprofilen" arbeiten, die gewisse Plugins checken und zu setzende Routings beinhalten. Wenn ein Track nun einem solchen Trackprofil entspricht, dann wird das Profil auf den Track angewendet.
Die derzeitigen wären:

StudioLink
StudioLinkOnAir
Soundboard
Andere Tracks

Dazu bau ich was in die Ultraschall-API rein und implementier das.

Ersteres zur 4.1, Zweiteres eher zur 4.2.

**Comment by mespotine** [comment]
Idee: das vielleicht über Tracktemplates zu lösen, die an einer bestimmten Stelle abgelegt werden und deren Settings fürs Magic Routing ausgelesen werden:
Tracks mit der gleichen FX-Konfiguration wie in den TrackTemplates bekommen das Routing aus den TrackTemplates spendiert.
Solche Templates müssen für die Fälle Pre-Show, Recording und Editing angelegt werden an dem entsprechenden Ort.

Möglicher Ort wäre: 
Ressourcenfolder/Ultraschall/MagicRouting/

und dort Unterordner für PreShow, Recording, Editing

@rstockm 

Das wäre ein ziemlich umfangreicher Umbau des MagicRoutings von mir(eventuell eine quasi Neuimplementation), die es aber prinzipiell auch möglich macht von UserSeite aus seine eigenen MagicRouting-Presets reinzubauen, ohne dass das von Dir per Hand hardgecodet werden muss(wie es derzeit ist).
Einziges potenzielles Problem: Wie macht man parallele Routings für ähnliche Tracks.

Beispielsweise: Wenn ich 4 Aufnahmetracks habe, die aber alle unterschiedliche HWOuts haben für Kopfhörerausgänge z.B., wie differenziere ich die per MagicRouting? FX würde da nicht helfen als Unterscheidungskriterium. 
Eventuell Trackname? Oder irgendwas Anderes? Hab da noch keine wirklich gute Idee...

**Comment by rstockm** [comment]
Ich würde das zur 4.1 nicht oder nur äußerst ungern anfassen wollen. Und verweise darauf, dass nutzerseitige Routing-Snapshots (4 Stück an der Zahl) ganz normal weiter funktionieren für Sondersituationen.
