### ISSUE TITLE
Action Liste aufräumen

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#33]
Es gibt eine Reihe von Einträgen in der Actions-Liste, die sich sehr zombihaft verhalten:

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/3195116/37373801-77e2a982-2718-11e8-9572-6bc39c939bb1.png">

alle die _nicht_ komplett groß geschrieben sind in der Command_ID sind kaputt. Teilweise absurd, etwa:

`ACT 0 0 “Ultraschall_ZoomToSelection” “ULTRASCHALL: Zoom to selection 40031" _Ultraschall_Remove_Studiolink_FX`
müsste heißen:
`ACT 0 0 “Ultraschall_ZoomToSelection” “ULTRASCHALL: Zoom to selection” 40031`

Das sind alles sehr alte Einträge, teilweise aus der 1.0 - gut möglich dass REAPER da mal die Logik geändert hat, sie lassen sich etwa nicht mehr über die REAPER GUI editieren.
Ich kümmere mich drum

**Comment by mespotine** [comment]
Die Ressource fürs Editieren in der kb.ini:

http://mespotine.de/Ultraschall/reaper-kb.ini.html
