### ISSUE TITLE
[BUG] 4.1 - Export Assistant: Finalize MP3 löst nicht aus, wenn ExportMP3-Status unknown ist

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#334]
Wenn der Export-Assistant nicht weiß, ob ein MP3 erstellt worden ist, löst(unter Windows) der Finalize MP3-Button nicht aus.
Das vorherige Verhalten war, wenn unbekannt ist welche Datei verwendet werden soll, zeigt das Plugin einen Auswahldialog an, wo man auswählen kann, welche MP3-Datei stattdessen verwendet werden soll.

Vielleicht fehlt noch das Plugin für Windows im Master, denn die Action selbst scheint schon in der ActionList zu fehlen.

**Comment by rstockm** [comment]
Gelöst durch https://github.com/Ultraschall/ultraschall-portable/commit/e4df63e21427628dd4aae4fc00b1389819710755

Bitte mal testen...
