### ISSUE TITLE
[BUG] Ultraschall 4.1: Soundcheckfenster Anzeigebug

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#335]
Einmal die Sekunde ploppt beim Soundcheck die Größe des Fensters kurz auf riesig, wenn All is Well ist.

![FensterZoich_Problem](https://user-images.githubusercontent.com/4251851/89124553-3ecf0300-d4d8-11ea-95d5-8e185a8e58ea.gif)

**Comment by rstockm** [comment]
Ist auf dem Mac nicht so... und in dem GIF ist auch keine Änderung zu sehen?
Eventuell nochmal Windows 10 testen...

**Comment by mespotine** [comment]
Schau mal im Gif am rechten unteren Rand des Soundcheck-Fensters. Da ploppt ne Linie einmal die Sekunde auf. 

Das passiert nur, wenn All is Well angezeigt wird, was meiner Erinnerung nach ne automatische Fenstergrößenanpassung hat. In allen anderen Modi ist alles in Ordnung.

Irgendwo scheint da das Fenster einmal größer und sofort wieder kleiner gestellt zu werden, also ein gfx.init("") quer zu laufen.

Wenns auf Mac nicht auftaucht, liegts wohl eher dran, dass der Effekt zu schnell passiert und daher nicht zu sehen ist.

**Comment by mespotine** [comment]
Die Frage ist also: Was macht der Soundcheck bei All is Well mit dem Fenster anders als sonst und kann man das reproduzieren. Wenns nen Bug auf Reaper-Seite ist, könnten wir den so reporten.

**Comment by rstockm** [comment]
Ok danke, ich schau mal rein.

**Comment by rstockm** [comment]
Möglicherweise behoben durch https://github.com/Ultraschall/ultraschall-portable/commit/465396e936e979ef2e80fef1387439cbbdf6f23b auf dem Master, bitte testen.
