### ISSUE TITLE
[ENHANCEMENT] Soundcheck: Unklar, wann der "Unsaved Project"-check zuschlägt.

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#336]
Sowohl vom Verhalten her als auch vom Hilfetext in den Settings ist unklar, wann der Unsaved-Project-Soundcheck zuschlägt.
Ich konnte ihn triggern aber erst, wenn ich Aufnahme starte mit einem Track gerecarmed. Er sollte da schon vorher zuschlagen oder klar sein, wann er das tut.
Während der Aufnahme abspeichern könnte zu nem kurzen Aussetzer im Signal führen(hab ich häufiger).

**Comment by rstockm** [comment]
„you just armed a track for recording“ ist die Ausschrift, das Verhalten ist unverändert seit der 4.0: sobald mindestens ein Track auf recarm geschaltet ist (und das Projekt nicht gespeichert) wird ausgelöst. 
Das ist in jedem Fall vor dem Recording (wichtig,
auch um da Stress rauszunehmen) und wiederum nicht so früh, dass man sich die Tracks nicht erst mal in Ruhe anlegen kann.

**Comment by mespotine** [comment]
Ok, dann sollte die Info aber noch in den Hilfetext der Settings. Damits irgendwo steht.

![image](https://user-images.githubusercontent.com/4251851/89126384-8e67fb80-d4e5-11ea-9d88-400157f3fb8c.png)

**Comment by rstockm** [comment]
Gelöst mit https://github.com/Ultraschall/ultraschall-portable/commit/b941a7c9aad9daef3dda083d5a1f5cda97abbbcd
