### ISSUE TITLE
[BUG] Theme-Anzeigebug

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#337]
Unter Windows:

Wenn man SetUp oder Storyboard-View anklickt, erscheinen folgende Artefakte, die zur 4.0 nicht aufgetaucht sind.

Rechts und unten untern obersten RoutingButton erscheint wohl Fensterränder. Vielleicht von der Ultraclock?

![image](https://user-images.githubusercontent.com/4251851/89124817-2233ca80-d4da-11ea-87dc-66976166c10b.png)

Ich weiß nicht ob das nen Reaper-Problem ist oder ob was am Theme/den Screensets braun ist.

**Comment by rstockm** [comment]
![image](https://user-images.githubusercontent.com/3195116/89900466-146dfb80-dbe4-11ea-970c-98ee5fa9f7f6.png)

Unter Windows 10 nicht reproduzierbar. Werde für den Beta-Test darauf hinweisen, dass die Leute darauf achten sollen.
