### ISSUE TITLE
[BUG] Ultraschall 4.1: Zwei Soundchecks erzeugen noch nil-errors mit Insert recording

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#339]
I'll investigate this.

**Comment by mespotine** [comment]
Der Soundcheck "Unsaved Project" verträgt sich nicht mit 
Script: ULTRASCHALL: Insert recording at editcursorposition without creating takes(ripple insert recording).

Unsaved Project-Soundcheck muss aktiviert sein.

1) erstelle neues Projekt
2) erstelle Track und nehme etwas auf
3) nimm innerhalb dieser Aufnahme nochmal etwas mit Insert Recording auf

Nach ein paar Sekunden kommt die Fehlermeldung:

![image](https://user-images.githubusercontent.com/4251851/89125040-d84be400-d4db-11ea-8f7a-76ccfaece723.png)

Alle paar Sekunden wird diese Meldung neu angezeigt. Diese verschwindet sofort, wenn man den Unsaved Project-Soundcheck ausschaltet.

**Comment by rstockm** [comment]
Eklig zu finden der Fehler - Schuld war Reihenfolge der Exit-Funktionen im Soundcheck. Hätte potentiell auch an anderen Stellen zu Problemen führen können.
Gelöst durch:
https://github.com/Ultraschall/ultraschall-portable/commit/d9dc2dadf7cc9c6022cf0750ccd1cf1a2e5e0447
