### ISSUE TITLE
[BUG] Ultraschall 4.1: MarkerDashboard - Text des Edit Chapter URL Dialogs passt nicht ins Fenster

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#340]
Der Anzeigetext ist zu lang und passt nicht. Vielleicht eher in den Titel des Fensters verfrachten?

![image](https://user-images.githubusercontent.com/4251851/89125216-1a295a00-d4dd-11ea-9668-f1541e352c0d.png)

**Comment by rstockm** [comment]
Hm hatte ich so aus dem PR übernommen - auf dem Mac sieht es auch gut aus. Vielleicht mal Windows 10 testen...

**Comment by mespotine** [comment]
Mach ich.

**Comment by rstockm** [comment]
Ist auch auf Windows 10 so. Wird gelöst durch:

https://github.com/Ultraschall/ultraschall-portable/commit/a79be21732b7075935c4e175592c1426c20bba35
