### ISSUE TITLE
[ENHANCEMENT] Follow/ZoomOut Buttons besser ausrichten zur Main Toolbar

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#341]
Wenn man noch nen Separator an die erste Position der Floating Toolbar 1 packt, kann man wunderbar die Höhe der Main Toolbar so anpassen, dass die Buttons besser ausgerichtet sind zueinander.
Müsste man vermutlich als Screensets abspeichern.

![image](https://user-images.githubusercontent.com/4251851/89125483-20203a80-d4df-11ea-96a9-114ca2161219.png)

(vorher vs nachher)

Ist zwar nur nen Detail aber macht optisch mehr her.

**Comment by mespotine** [comment]
Muss man mal schaun, ob das Alignement erhalten bleibt, wenn man Reaper auf HiDPI/Retina nutzt(habs nur auf alter Auflösung getestet).

**Comment by rstockm** [comment]
Der Abstand oben ist eigentlich abhängig von der REAPER-Fensterhöhe. Wenn man die verschiebt, ändert sich auch der Ansatzpunkt oben. Mir ist leider kein Weg bekannt, dieses responsive Verhalten zu beeinflussen? Man kann es zwar für irgendeine Fensterhöhe optimieren, aber alle anderen sind dann eben zu hoch oder zu niedrig.

**Comment by mespotine** [comment]
Ah, ich seh schon. Ok, dann geht das leider nicht.
