### ISSUE TITLE
[BUG] Es fehlen diverse Shortcuts in der kb.ini im Master seit geraumer Zeit

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#343]
z.B.
- rauf und runter für zoom

Eventuell weitere?

**Comment by rstockm** [comment]
Rauf/runter sollte jetzt den Arrangeview verschieben. 
Wir sollten eine zentrale Doku-Stelle wählen - md-file hier im Git, oder im Wiki? Wo wir verbindlich die Tastatur-Shortcuts dokumentieren und dann immer in den beiden Dateien nachziehen können.

**Comment by mespotine** [comment]
Wiki wär am Besten. Dann kann es jedeR einsehn und eventuell coolen Kram mit anstellen. Als md oder im Git findets niemand.

Ok, dann close ich mal das Issue wieder.

Ich versuch mal ne Liste automatisch zu erstellen aus der ActionList/kb.ini heraus, die wir später auch parsen können.
Dann haben wir auch die Shortcutcodes für Mac, Windows und Linux. Manches unterscheidet sich da ja.

**Comment by rstockm** [comment]
ToDo: Anpassung/Test auf Windows.
