### ISSUE TITLE
[BUG] Ultraschall 4.1: u.U. schlägt "Record from end"-Soundcheck bei "Preview-Rec mit Dialog" zu.

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#344]
Manchmal kann es sein, dass man Preview-Recording machen will für eine Spur und man beim Wiedereinsatzpunkt noch eine Spur laufen hat, die nicht scharfgeschaltet ist.
Z.B. Man spricht selbst einen Dialog ein, wo die Sprechenden ineinander übergehen. Der eine fällt dem Anderen ins Wort.
Praktisch läuft also Sprecher 1 noch, dem man als Sprecher 2 ins Wort fallen will. Dann startet man die Preview-Recording-Aufnahme vor Projektende und zack: schlägt der Soundcheck zu.

Man kann also nur Text nach Text einsprechen, nicht parallel. 

Dieses Verhalten ist kurioserweise nur Previewrecording mit Dialog, nicht im Previewrecording mit voreingestellter Aufnahmedauer(ich konnte es zumindest nicht triggern).

Hier nen Beispielgif für das Verhalten.
![PreviewRecording-bug](https://user-images.githubusercontent.com/4251851/89126119-827b3a00-d4e3-11ea-90be-9cde9380c992.gif)

**Comment by rstockm** [comment]
Gelöst durch https://github.com/Ultraschall/ultraschall-portable/commit/6ed031d5f5d81d0bf51382947239cee6635c0852
