### ISSUE TITLE
[BUG] Ultraschall 4.1 - ExportAssistant: Drag n Drop funzt nicht in "smaller slots" auf Windows

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#351]
Die kleineren Slots können nicht be drag n dropped werden. Es passiert meist nichts. Manchmal wird aber der "Hauptslot" belegt.

![temp](https://user-images.githubusercontent.com/4251851/89735907-01cdb800-da66-11ea-9658-8c1bb5f7e469.gif)

**Comment by mespotine** [comment]
Der Hauptslot funzt zuverlässig. Jpgs im rechten oberen Slot fügen oft Cover im Hauptslot ein, Png selten bis gar nicht.

Ich weiß nicht, ob das so gedacht ist....

**Comment by rstockm** [comment]
Danke, ich vermute mal dass ich da einen Umrechnungs-Fehler Retina/Non-Retina drin habe in den Dropzones. Ich muss das morgen mal dringend auf meinem Windows-Lappi aufsetzen.

**Comment by rstockm** [comment]
Vermutlich behoben durch

https://github.com/Ultraschall/ultraschall-portable/commit/b8e31a597afe874eaa4b776115526a27a66fd170

ToDo: Check auf Non-Retina Display

**Comment by rstockm** [comment]
Funktioniert auch auf Non-Retina Win 10 Installation. Es fehlten im GIT noch der Folder für die Covers.
