### ISSUE TITLE
[BUG] Ultraschall 4.1: Export Assistant - extrem hohe CPU-Auslastung

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#352]
Wenn ich den Export Assistant öffne, geht die CPU-Auslastung extrem in die Höhe.
Reapers GUI reagiert sehr laggy dadurch, inklusive die normalen Menus.

![CPU-Auslastung-ExportAssistant](https://user-images.githubusercontent.com/4251851/89736056-15c5e980-da67-11ea-9a76-62808ca0c0da.gif)

**Comment by rstockm** [comment]
Getestet auf einem 3 Jahre alten 2-Kern i5 Laptop Windows 10: die Last bei einem leeren Export-Fenster liegt bei 16%. Fügt man mindestens ein Cover-Bild hinzu, steigt die Last auf ca. 24% an. Die GUI bleibt jederzeit flüssig.

Wird nochmal angegangen beim Umstieg auf eine neue GUI-Engine

**Comment by rstockm** [comment]
Durch Umbau der GUI Lib gelöst.
