### ISSUE TITLE
Action "ULTRASCHALL: Skip loop playback absolute" sollte nur im Follow-Mode den View ändern

### ISSUE THREAD

**Issue by timpritlove** [Ultraschall/ultraschall-portable#353]
Bei der Aktion "ULTRASCHALL: Skip loop playback absolute" führt der Sprung an den Beginn der Time Selection dazu, dass der aktuell eingestellte View sich ändert und eine manuell gewählte Ansicht entsprechend geändert wird.

Das ist etwas ungünstig, wenn man eine Ansicht gewählt hat, bei der man z.B. das Ende der Selektion im Blick haben möchte und ggf. durch die verschiedenen Durchläufe, die durch die Aktion angestossen wird, genauer einstellen möchte. In einer großen Zoomstufe springt nun Reaper immer wieder an den Anfang der Selektion und man muss jedes Mal manuell wieder an das Ende der Selektion springen.

Dieses sollte im Idealfall nur dann passieren, wenn der Follow Mode ausgewählt ist.

**Comment by mespotine** [comment]
gelöst durch #430
