### ISSUE TITLE
[ENHANCEMENT] Support for Ardour or Bitwig

### ISSUE THREAD

**Issue by supersexy** [Ultraschall/ultraschall-portable#392]
Ok, so I understand that this is Reaper only - anyway i would like to ask - is there any remote chance of making this a VST plugin that would work in Ardour / Mixbus or Bitwig Studio?

**Comment by rstockm** [comment]
"making this a VST plugin" - well.
Ultraschall consists of these components:
- a Theme
- ca. 200 LUA-Scripts
- backgound demons
- JSFX Plugins
- 1 VST Plugin
- C++ Scripts
- Custom API with 1200 Endpoints

All of them hand-tailored against the REAPER infrastructure and APIs.
So no, there is no chance to capsule any of this into a VST.

That being said, Ardour would be an interesting platform. But this would be a complete different project.
