### ISSUE TITLE
[Website] Please stop low contrast anti-eye war - more love for people that read your website

### ISSUE THREAD

**Issue by supersexy** [Ultraschall/ultraschall-portable#393]
Grey font is for disabled items or text that you should NOT read, like small print in contracts of shady car dealers or something like that. It is totally irrational and very bad idea to use grey color font - even more on grey background - for text that should be actually read by people. Please do not do that. It is like recording noisy audio very quiet and putting it on a white noise background sound. Oder wie weisser Adler auf weissem Grund.

Also take a look at https://www.contrastrebellion.com/ to learn why you do not want to be low-contrasty in general.

**Comment by supersexy** [comment]
This is just a screenshot to document the really extreme seh-behinderten-feindlichkeit of your site, an extraordinary horrible example of this practice. 

![image](https://user-images.githubusercontent.com/11744844/109001050-bc40a780-76a4-11eb-85bf-b2a73bac23b2.png)

Please do not fight people that already have enough problems with looking at monitors. Thanks.

I need to add one more thing: podcasts are one really important source of information for people with bad eyes - it is a very bad example of extraordinary ignorance to design a website that promotes tools for producing podcasts in a way that especially these people will have bad problems with. I have not seen such level of Behinderten-Hass for a long time.

**Comment by rstockm** [comment]
Thank you for addressing this issue, I've increased the overall contrast of the site.
On a sidenote: many texts on the page https://www.contrastrebellion.com/ lack contrast, too - that's a bit weird.

And on a personal note: "I have not seen such level of Behinderten-Hass for a long time."
This is - hands down - quite offensive.
I value your input, but please choose your words wisely, thanks.
