### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shiller79** [Ultraschall/ultraschall-portable#394]
**What were you doing?**

1. Ultraschall starten, ohne das "Show LUFS (Master)" in der Ultraclock aktiv ist
2. Links klick auf die Ultraclock 

**What did you expect to happen?**
Nichts

**What happened instead?**
ReaScript Error: ...ppData\Roaming\REAPER\Scripts\ultraschall_ultraclock.lua:712: attempt to perform arithmetic on a nil value (global 'date_position_y')

**Version of Ultraschall**
5.0.1

**Operating system and language running Ultraschall**
Windows 10 20H2

**REAPER version running Ultraschall**
6.25

**Audio interface model and used firmware incl. version**

**Screenshot(s)/video(s) showing the problem:**
![screenshot1](https://user-images.githubusercontent.com/7950461/112558518-3ca31700-8dcf-11eb-8829-06f6ffd5f91d.png)
![screenshot2](https://user-images.githubusercontent.com/7950461/112558520-3e6cda80-8dcf-11eb-82eb-2d5a70cac9ac.png)

**Comment by shiller79** [comment]
ich konnte den Fehler beheben indem ich in der ultrashall_ultraclock.lua die Zeile 514 (date_position_y = txt_line[2].y*height+border) in die Zeile 449 hochgeschoben habe. Hab mich jetzt aber keinen Pull-Request getraut, weil ich den Code zu wenig kenne um abschätzen zu können ob das irgendwelche Seiteneffekte hat.

**Comment by rstockm** [comment]
Ich denke der sinnvollere Weg ist die Anfrage, ob überhaupt die LUFS in den Settings gerwählt ist, wenn nicht wird die Klickfläche komplett ignoriert:

https://github.com/Ultraschall/ultraschall-portable/commit/c0b6b1dce925fad8688c8098f0aaa9ecc168c7c6
