### ISSUE TITLE
[BUG] MagicRouting in __startup überschreibt Routings

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#399]
Die __startup.lua stellt einen Default-Modus fürs Magic Routing ein. Der ist aber buggy.

Folgendes Problem:
Ich erstelle ein Projekt mit meinem eigenen Routing. Ich habe Magic Routing ausgeschaltet, speichere das Projekt ab.
Wenn ich jetzt Ultraschall schließe und neu starte, das letzte Projekt also gleich mitgeladen wird, so überschreibt die __startup.lua das customisierte Routing beim Initialisiern von MagicRouting.

Das passiert nicht, wenn man das Projekt speichert, das Projekt schließt, Ultraschall beendet, Ultraschall neustartet, DANN das Projekt wieder lädt, dann bleibt das Routing erhalten.

Das Problem ist, dass das Initialisieren davon ausgeht, dass die im Projekt eingestellte MagicRouting-Config die ist, die eingestellt werden müsste und dann alles so setzt. 

Was es stattdessen machen sollte ist:
Nachschauen, ob ein MagicRouting gesetzt ist und wenn ja NUR den Toggle-State des Buttons setzen, nicht die Routing-Matrix. So bleibt das Routing erhalten.
Sollte kein MagicRouting-Extstate gesetzt sein, wird kein Toggle-State der Buttons gesetzt.  Also auch dann kein Routing setzen, weil es sein kann, dass man ein altes Ultraschall 3.1 Projekt zum Start geöffnet hat, welches noch kein MagicRouting kannte und im ExtState hat. 
Wenn dieses ein eigenes Routing besitzt, würde das auf diese Art auch weggebügelt, wenn automatisch ein Default-Routing gesetzt würde.

**Comment by frankbash** [comment]
schön das ich nicht der einzige bin dem es auffällt und so langsam genervt ist. wie haben Ultraschall 5 und es ist immer noch da dieser bug

**Comment by rstockm** [comment]
Das Verhalten bei im Projekt ausgeschaltetem Magic-Routing werde ich prüfen, hier sollte ein händisches Routing nicht überschrieben werden, richtig.

Das Hier sehe ich anders:

> Was es stattdessen machen sollte ist: Nachschauen, ob ein MagicRouting gesetzt ist und wenn ja NUR den Toggle-State des Buttons setzen, nicht die Routing-Matrix. So bleibt das Routing erhalten.

Das ist in vielen Fällen nicht das gewünschte Verhalten, denn: Die Aufnahme wird mit externem Soundinterface gemacht. Alles gespeichert, im Kasten. Es ist spät, alle müde. Am nächsten Tag wird geschnitten, Soundinterface ist ab, es wird die lokale Soundkarte genutzt. Die muss im Routing aber anders bespielt werden, damit man überhaupt was hört.

MagicRouting sagt im Kern aus: egal was du wie anstöpselst oder nicht, ich probiere immer das Beste daraus zu machen. Daher macht es Sinn, beim Start eines Projektes das Routing immer wieder den aktuellen Gegebenheiten anzupassen.

Im Manuellen Modus ist das anders, schaue ich mir an.

**Comment by mespotine** [comment]
Ist das Problem inzwischen gelöst, @rstockm

**Comment by mespotine** [comment]
Wird man in Ultraschall 5.1 in den Settings ausschalten können. Sprich: man kann einstellen, dass die letzte MagicRouting-Einstellung erhalten bleibt. War es ausgeschaltet, so bleibt es ausgeschaltet beim Reaper Neustart.
