### ISSUE TITLE
Play from mouse Cursor auch auf Tracks

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#4]
Die Mouse-Modifier Settings sind so umzustellen, dass ein Doppelklick in den Leerstellen zwischen Items ebenfalls abspielt.

**Comment by rstockm** [comment]
![image](https://user-images.githubusercontent.com/3195116/36636454-138f634c-19c8-11e8-9cf2-d40d4832ba69.png)

**Comment by lootsy** [comment]
Ich habe keine Ahnung, was zu testen ist.

"Play from mouse cursor auch auf Tracks" - das ging doch schon immer, oder?
"Doppelklick in Leerstellen zwischen Items"... - was ist in diesem Zusammenhang mit "Leerstellen" gemeint?

Kannst du das erläutern oder n Screenshot machen?
Ich kenn mich mit den "Fachbegriffen" nicht aus. Z. B. weiß ich nicht, was in Reaper ein "item" _genau_ ist. Ich hab da schon ne Vorstellung. Aber ob das stimmt... Keine Ahnung.

Ein Beispiel-Projekt hinzufügen? In dem das Problem auftritt und mit dieser Änderung nicht mehr?

**Comment by rstockm** [comment]
Hier sind die Begriffe mal dargestellt.
Das über einen Maus-Doppelklick auf einem Item das Abspielen ab dieser Position gestartet wird, gibt es erst seit der 3.1
Die gewünschte Erweiterung dieses Issues ist nun: auch in den Leerstellen zwischen Items soll das genauso klappen, da passiert bissher: nix.

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/3195116/36939789-813d0344-1f37-11e8-9517-7fe1e283e4b8.png">

In der Regel reicht ein gründlicher Test um so ein eher triviales Issue zu schließen - es gibt hier keine Abhängigkeiten zu anderem Code, es ist noch nicht mals eine LUA Funktion sondern nur 08/15 REAPER-Settings.

Da ich gerade keinen Window-Rechner mit Git am Start habe ist im Kern die Frage: verhält sich das unter Windows jetzt auch so wie gewünscht.

**Comment by lootsy** [comment]
Dieses Issue hat aktuell den (noch) offenen PR https://github.com/Ultraschall/ultraschall-portable/pull/10
Nach Bestätigung von meo und merge würde ich dieses Issue schließen.

**Comment by rstockm** [comment]
Meines Wissens nach: nur @mespotine alle anderen sind auf dem Mac unterwegs. Zur Not kann ich auch noch ein Win Laptop aufbauen.

**Comment by lootsy** [comment]
Hi @rstockm, danke für die Antwort.
Ich hoffe, dass das erstmal reicht. Das zeigt mir welche Verantwortung ich trage. ;-)
Hab jetzt mal meine Win Installation etwas gepimpt, so dass ich mehr Platz habe. So hoffe ich, dann auch besser entwickeln / testen zu können.
Ich glaube mit den beiden kommen wir erstmal hin. Schön wäre ja, wenn wir so etwas wie Test-Automatisierung haben.

**Comment by mespotine** [comment]
@rstockm Ja, wir brauchen ganz dringend mehr Windows-Testende, vorrangig welche, die Ultraschall auch produktiv auf Win einsetzen.
Hat fairsein nicht mal angefragt? Er nutzt US auch auf Win10, wo es die meisten Issues mit der ultraschall.ini bislang gab...

**Comment by rstockm** [comment]
@mespotine ja den könnte man in der Tat mal anfragen. Mach ich mal.

**Comment by lootsy** [comment]
> mehr Windows-Testende, vorrangig welche, die Ultraschall auch produktiv auf Win einsetzen

bin da dran, dauert aber noch. Bin auch "nur" _ein_ Mensch... ;-)
