### ISSUE TITLE
[BUG] Export Assistent: MP3 wird nicht finalisiert wenn Dateinamen mit Regionen exportiert

### ISSUE THREAD

**Issue by deermo** [Ultraschall/ultraschall-portable#403]
Hallo,

vorerst: Geniales Projekt, geniale Software - vielen Dank.

Unser Podcast hat regelmäßig zwei Teile, die wir als Region markieren. Als Export-Setting nutzen wir daher als Bounds "Project Regions", und als File Name "$project - $region". In dieser Einstellung werden die Kapitalmarken etc. leider nicht in die MP3-Dateien übertragen.

Ist natürlich ein benutzerdefiniertes Setting und kein Drama, aber ggf. machen das auch andere? 

Viele Grüße,
Moritz

**Comment by mespotine** [comment]
Wie exportierst Du die Metadaten bislang denn?
