### ISSUE TITLE
[BUG] Linux: Fenstergrößen bei skalierten Bildschirmauflösungen

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#409]
Wenn man Ubuntu mit einer skalierten Bildschirmauflösung betreibt (etwa auf einem Retina-Display), hier 150%, so werden die Fenstergrößen unserer Ultraschall-GUI Fenster allesamt falsch berechnet.

Über die REAPER-Zoom-Einstellungen wird man da nicht viel reißen können, im worst case muss man einen interaktiven Guide bauen der den Skalierungsfaktor übernimmt und überall anwendet.

![grafik](https://user-images.githubusercontent.com/3195116/154771226-d3917f5e-5233-4e34-abb0-592d167206ed.png)

**Comment by mespotine** [comment]
Ich würde ja nen unsichtbaren Punkt rechts unten positionieren in der Gui. Und wenn dieser Punk nach der Initialisierung(und nur dann) außerhalb des sichtbaren Bildes ist(größer als gfx.w gfx.h), dass einfach vergrößern und neu positionieren(Position des Punktes ist dann kleiner als gfx.w, gfx.h)
Das wäre einfacher als was Anderes komplizierteres zu bauen.

**Comment by mespotine** [comment]
Wird in US6 mit der neuen Gui-Lib gelöst, die Skalierungen von 1x bis 8x automagisch macht.
