### ISSUE TITLE
[BUG] Ultraschall Settings hinterlässt leeres Fenster sobald man Fenstergrösse ändert [linux]

### ISSUE THREAD

**Issue by nethad** [Ultraschall/ultraschall-portable#413]
https://user-images.githubusercontent.com/222981/155595198-29cb4ff6-5355-4d3f-9c76-1d8157dedf49.mp4

**Comment by mespotine** [comment]
Kann ich für Windows bestätigen.

**Comment by mespotine** [comment]
Wird mit der neuen guiLib für Ultraschall gelöst. Bis dahin isses höchstwahrscheinlich ein Won'tFix.

**Comment by mespotine** [comment]
Gelöst durch #469
