### ISSUE TITLE
Lock (music) track against (ripple) cut

### ISSUE THREAD

**Issue by nitramred** [Ultraschall/ultraschall-portable#417]
As discussed with @mespotine (https://sendegate.de/t/spur-gegen-schnitte-schuetzen/15384) it would be great to lock one or more tracks against any kind of editing. I often use music with my podcasts and it's a big source of error if I edit out an "ähm" in the intro only to realize that the intro music was shortened as well. Thanks in advance!

**Comment by rstockm** [comment]
Zu klären wäre, welche anderen (Schnitt) Actions außer Ripple-Cut hiervon noch betroffen wären.

**Comment by nitramred** [comment]
Falls das noch eine Rückfrage war: Ich hatte mir so was vorgestellt wie das "Ebene sperren" in einem Bildbearbeitungsprogramm. Also das Sperren des Tracks gegen jede Art von Veränderung.

**Comment by mespotine** [comment]
Ich glaube was Ralf meint ist eher, ob sowas wie die S Taste oder Entf-Taste, die ja auch auf den Schnitt Einfluss nehmen, da mit berücksichtigt werden müssen oder sollten.

Ich glaube, ich würde es erstmal nur als Option in RippleCut einbauen und abwarten. Wenn Leute sagen, dass sie es auch in anderen Actions wünschen, können wir gezielt nach Usecases fragen, denn ich glaube bei Split und Entfernen kpmmts dann doch auf die Details an.
Dazu hätte ich gerne praktische Beispiele um daran das Finetuning zu betreiben.
