### ISSUE TITLE
Item in Finder/Explorer anzeigen

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#42]
Manchmal möchte man schnell die Quelldatei eines Items im Finder/Explorer sehen. Ein Script oder eine zusätlicher Eintrag im Kontextmenü "find in Finder/Explorer" wäre gut.
Im Avid Mediacomposer heißt die Funktion "reveal file". Es wird der Finder geöffnet und die entsprechende Datei markiert. Auf dem Mac können sogar mehrere markiert sein (natürlich nur, wenn alle in selben Ordner sind)

**Comment by mespotine** [comment]
Was ist dabei ein Beispiel-Usecase? Schließlich haste ja alle Items ja schon im Projekt....

**Comment by mespotine** [comment]
Könnte in der nächsten Version von SWS möglich sein:
[https://github.com/reaper-oss/sws/pull/1000](https://github.com/reaper-oss/sws/pull/1000)

**Comment by mespotine** [comment]
https://mespotin.uber.space/Mespotine/Ultraschall/Reaper_Api_Documentation.html#CF_LocateInExplorer

**Comment by rstockm** [comment]
ToDo: in Kontextmenü einbauen (Mausliebe)

**Comment by mespotine** [comment]
Hat noch n Bug, wenn kein Item vorhanden ist/ausgewählt.

**Comment by mespotine** [comment]
Done.
