### ISSUE TITLE
Podcast Metadata in Ultraschall(Phase 1)-Sammelissue

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#421]
Hier einfach alles reinwerfen, was an Feedback und Dokumenten/Bildern für Phase 1 vom Podcast Metadata Projekt(Phase 1) relevant ist.

Hier die Doku zum derzeitigen Entwicklungsstand:

https://mespotin.uber.space/Ultraschall/Ultraschall_PodcastMetadata_Introduction.html

**Comment by mespotine** [comment]
Platzhalter für eventuelle Orgasachen für Phase 1...

**Comment by mespotine** [comment]
Platzhalter für eventuelle Orgasachen für Phase 1...

**Comment by mespotine** [comment]
Platzhalter für eventuelle Orgasachen für Phase 1...

**Comment by Bra-Ger** [comment]
Hallo, Ich habe mal versucht die gestellten Fragen zu beantworten ich habe eine PDF Datei hier angehängt (Das Original ist in MD) 
[Methadata_Phase1.pdf](https://github.com/Ultraschall/ultraschall-portable/files/9542437/Methadata_Phase1.pdf)
