### ISSUE TITLE
Snap/Grid Settings ändern

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#43]
Vorschlag: in den Snap/Grid Settings “Media items snap at:” auf “Snap both start/end” stellen, dann schnappts auch am Ende eines Items, wenn man was nach rechts verschiebt.

**Comment by rstockm** [comment]
Problem: das wird nur pro Projekt gespeichert. Siehe:

https://www.reddit.com/r/Reaper/comments/914gfe/saving_reapers_default_snap_settings_or_workaround/

Ich werde das in die Templats mit aufnehmen, aber in einem leeren Projekt hat das dann keine Auswirkung.

**Comment by rstockm** [comment]
Umgesetzt in:

https://github.com/Ultraschall/ultraschall-portable/commit/d4df049f516935b45d9a85353ad6bf534536c924
