### ISSUE TITLE
__startup.lua sollte auch nen kleinen "Ultraschall korrekt installiert"-Check haben.

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#45]
Weil es im Sendegate ständig wieder aufkommt, dass Leute das Theme installieren, aber Ultraschall selbst nicht sauber installiert haben, würd ich gern in die __startup.lua noch ein paar kleine Checks einbauen, der prüft, ob Ultraschall installiert wurde. Zumindest, ob SWS, das ultraschall-plugin existieren und SWS-Funktionen aufrufbar sind.

Hintergrund: im Plugin selbst gibts einen Check, der zuschlägt, wenn die Installation nicht korrekt durchgeführt wurde. Wenn aber das Plugin nicht sauber installiert wurde, weil man das Theme vorher installiert (wie es in der Mac-version möglich ist), findet der Check nicht statt und es wird eine Fehlermeldung ausgegeben, dass eine SWS-Funktion nicht gefunden wurde.

Ein Hinweis, dass man die komplette Installationsanleitung befolgen muss und vielleicht ein automatisches Öffnen der Installationsanleitung wäre da hilfreich als Feedback für die User...

**Comment by mespotine** [comment]
Prinzipiell würd ich mit der Api-Funktion reaper.file_exists() das Vorhandensein der Plugins checken und im Anschluß nochmal prüfen, ob irgendeine SWS-Funktion existiert, beispielsweise mit:
```
if reaper.BR_Win32_GetPrivateProfileString==nil then 
        reaper.MB("Ultraschall nicht sauber installiert","Fehler",0)
        openurl("pfad/installation.html")
end
```

**Comment by rstockm** [comment]
>Prinzipiell würd ich mit der Api-Funktion reaper.file_exists() das Vorhandensein der Plugins checken und im Anschluß nochmal prüfen, ob irgendeine SWS-Funktion existiert, beispielsweise mit: ...

@mespotine eigentlich gibt es in der Startup auch schon diesen Check, da das Plugin nach erfolgreicher Installation ein Flag in die Ultraschall config schreibt. Das ganze Verfahren ist aber eher wackelig, daher: ja, gerne robuster machen. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
