### ISSUE TITLE
Beim Export von Chaptermarks werden auch Regions exportiert

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#46]
Exportiert man mit dem MP3 Export Dialogdingsi eine chapters.txt landen dort auch Regions drin.

**Comment by heikopanjas** [comment]
Sollen die Regions nur aus der `chapters.txt` raus, oder auch aus dem MP3/4-Target?

**Comment by mespotine** [comment]
Den Export in die chapters.txt hab ich in meiner Api schon gehackt, können wir also in pure Lua umwidmen.

@heikopanjas 
Ich glaub, Regions machen in MP3s/MP4s wenig Sinn, denn die meisten nutzen Regions bislang für Editier und Render-Sachen, nicht für Marker-Sachen...
