### ISSUE TITLE
[BUG] JSFX Effects missing in the last master builds in Reaper 7

### ISSUE THREAD

**Issue by richardguenther** [Ultraschall/ultraschall-portable#466]
Hey ihr,

in den letzten builds auf dem main-branch fehlen (unter windows zumindest) die jsfx effekte (also z.B. der Ultraschall Dynamics Effekt in der Standard-Chain.)
Der Audiogram-Build, den Ralf nach gemacht hat hat die jsfx noch drin.
Liebe Grüße
richard

**Comment by mespotine** [comment]
Kannst Du den aktuellsten Main-Branch mal testen? Da ist das Audiogram mit drin(hab ich erst vor ein paar Minuten gemerged).

**Comment by richardguenther** [comment]
> Kannst Du den aktuellsten Main-Branch mal testen? Da ist das Audiogram mit drin(hab ich erst vor ein paar Minuten gemerged).

Hi,
den hatte ich gerade getestet und gedacht, dass es damit vielleicht wieder ginge - aber die jsfx effekte fehlen. 
VST Effekte sind da.

**Comment by mespotine** [comment]
Schau ich mir mal an.

**Comment by richardguenther** [comment]
> Schau ich mir mal an.

Hey.

Es liegt an meiner zu progressiven Reaper-Version (hatte es mit 7.02 probiert).

Ich probieren noch etwas herum, aber mit der aktuellen main-branch funktioniert es mit 6.83!

Verzeih den Aufwand!
liebe Grüße
richard

**Comment by mespotine** [comment]
Ja, Reaper 7 ist ausdrücklich nicht supportet. Das kommt erst zur Ultraschall 6.
