### ISSUE TITLE
Kapitel-Timecodes, wenn man eine Range exportiert hat stimmen nicht.

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#47]
Wenn ich in einer Sequenz zwei Teile einerSendung habe, dann stimmen natürlich nach dem Export des zweiten Teils die Timecodes der Kapitel nicht mehr. Man müsste checken, ob die Timecodes mit der Länge der Datei korespondieren oder, fragen ob es einen Offset gibt...

**Comment by mespotine** [comment]
Das Timecode-Offset-Problem überlege ich schon auch sehr lange, seit ich an der Api schraube. Mit meinen Funktionen kann man sich gezielt nen Zeitbereich angeben, so dass die Offsets stimmen, könntest Dir also gezielt Skripte basteln, die das für Dich machen.

Was ich aber als schwierig empfinde ist, wie baut man das in einfach und leicht für die EndUser ein? Die Offset-Problematik kann leicht verwirrend werden...
