### ISSUE TITLE
[BUG] [Linux] Reaper crash when exporting video audiogram

### ISSUE THREAD

**Issue by nucleus-ffm** [Ultraschall/ultraschall-portable#473]
**What were you doing?**

1. open the export assistant
2. fill in the required information for the video audiogram
3. Export the video audiogram

**What did you expect to happen?**
successful exported video audiogram

**What happened instead?**
Reaper crashes. It seems that Reaper always crashes when you try to export WebM. Other formats work.

**Version of Ultraschall**
5.1 ([the repo at this point](https://github.com/Ultraschall/ultraschall-portable/tree/d4deb8bef38e3ed8c341cd21a673cfc64345cf29))

**Operating system and language running Ultraschall**
Linux - Fedora 39

**REAPER version running Ultraschall**
Reaper v6.27

**Proposed change**
use Reaper >= v6.83 and MP4 instead of WebM as the export format for the Video Audiogram.

**Error log:**
```
[libvpx @ 0x1f02680] v1.13.1
[webm @ 0x2741cc0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[webm @ 0x2741cc0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
./install-reaper.sh: Zeile 407: 27505 Getötet
```

**Comment by mespotine** [comment]
Does this happen also on 6.83 using WebM?
