### ISSUE TITLE
Ultraschall 5.1 - Release ToDos

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#474]
__KeyMap:__
  Shift+E für named Edit Marker hinzufügen

__Startscreen:__

  AudioGram, Render Preset-Menü, Online Hilfe
  Manuelles Ducking von Tracks, Outtakes, Ripple Cut 2.0

  Mastodon anstelle von Twitter

  Verlinkungen auf Tutorial-Seiten machen (Code Zeile 174 rund um den Suchbegriff startTutorial )

__Tutorial:__
  1)  Hinweis auf die Anleitung im Help/Documentation-Menu
  
  5)  Settings-Dialog updaten
  
  13) Export AudioGram - Text+Grafik
  
  14) Render Preset-Menü
  
  15) Quick Snippet Render
  
  16) Manual Ducking of Tracks
  
  17) RippleCut 2.0
  
  18) Outtakes

**Comment by nucleus-ffm** [comment]
9. Im Podcast Menü fehlt unter `Markers` die neue Funktion einen Editmarker mit  <kbd>Shift</kbd> + <kbd>E</kbd>  zu setzen.

**Comment by mespotine** [comment]
12. KeyMap in "Help: Ultraschall Keymap (Ultraschall)" ergänzen.
