### ISSUE TITLE
[BUG] Manuelles Ducking ist pre-FX; sollte post-FX

### ISSUE THREAD

**Issue by derjoram** [Ultraschall/ultraschall-portable#485]
Manuelles Ducking ist eine pre-FX action. Der US-dynamics Filter würde potentielle Änderungen in der Lautstärke pre-FX wieder rückgängig machen. Action sollte post-FX sein, damit sie das korrekt gepegelte Signal runterregelt.

**Comment by mespotine** [comment]
gelöst
