### ISSUE TITLE
MagicRouting

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#49]
Prepare al tracks for editing sollte die Routing-Matrix komplett leeren, alle Spuren auf den Master schicken (passiert schon) und den Master auf den Primären (ersten) Stereo-Output schicken.

**Comment by rstockm** [comment]
![image](https://user-images.githubusercontent.com/3195116/40272684-be979ebe-5bb1-11e8-8b14-3e91267e509e.png)

Links vorher, rechts nachher. M.E. können sogar sends auf den Aux (3/4) für Soundboard-Ducking hier gelöscht werden - das greift schon beim Recorden, im Zweifel duckt das sonst doppelt.

**Comment by mespotine** [comment]
Ist das so umsetzbar mit den Möglichkeiten der Api oder bräuchteste dafür noch was an Features?

**Comment by rstockm** [comment]
Issue wird erweitert als MagicRouting - die Abschaffung der Routingmatrix und komplette Automatisierung
