### ISSUE TITLE
Sound abspielen, wenn bei Play der Playcursor ne Kapitelmarke streift.

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#50]

**Comment by rstockm** [comment]
Die 50! Wir sind gespannt.
(nur ein Test der GitHub=>Rocketchat Integration)

**Comment by fernsehmuell** [comment]
Ergebnis der Recherche ist viel zu kompliziert und ragiert nicht immer so wie man es will, Metronom ist der falsche weg, um Sounds abzuspielen. Mespotine hatte auch was eleganteres gefunden.

**Comment by mespotine** [comment]
Wird gelöst durch #148 ohne Metronom, sondern mit Hilfe der neuen JS-Extension, die ne Preview-funktion mitliefert.
