### ISSUE TITLE
[BUG] 5.1 beta: Ultraclock error when clicking on LUFS meter

### ISSUE THREAD

**Issue by derjoram** [Ultraschall/ultraschall-portable#509]
**What were you doing?**
1. Re-installed Reaper + Ultraschall 5.1 beta
2. Recorded 20 sec of audio
3. Prepare all tracks for editing
4. doubleclick on LUFS meter in Ultraclock
5. Get error: "...pi//Modules/ultraschall_functions_Ultraschall_Module.lua:1477: bad argument #3 to 'TrackFX_GetFXName' (string expected, got no value)"
6. Ultraclock disappears

LUFS meter also displays a question mark at all times. "? LUFS"

**What did you expect to happen?**

Open LUFS meter

**What happened instead?**

Error

**Version of Ultraschall**

Ultraschall 5.1 beta build from 21.8.24
(btw: there is no "about Ultraschall" menu item in 5.1

**Operating system and language running Ultraschall**

macOS 14.6 on M1 Macbook Pro
English

**REAPER version running Ultraschall**
 
Reaper 6.25

**Audio interface model and used firmware incl. version**
 
independent of audio interface

**Comment by mespotine** [comment]
Ultraschall 5.1 requires Reaper 6.83 to work.
Could you to try again with Reaper 6.83 and report if things still don't work?
