### ISSUE TITLE
Clipping-Analyse während des Renderns

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#51]
Zu häufig passiert es mir, dass ich ein Projekt rendere und es gibt eine oder zwei Stellen, die in den roten Bereich gehen.
Reaper zeigt auch im Render-Progress-Fenster an, dass es CLippings gab, aber nie wo.

Das nervt, speziell, wenn ich Material habe, bei dem ich nicht mit Limiter oder Dynamics arbeiten kann, speziell bei Sachen die Musik enthalten, Hörspielen, Features, etc.

Daher brauchen wir eine "Clipping"-Analyse, während des Renderns, die mitloggt, ob es Clippings im Master-Track gibt und hinterher anzeigt, wo.

**Comment by mespotine** [comment]
Eine Möglichkeit wäre: Wir schleusen ein JSFX-Pegel-Analyse-Script ans Ende der Signalkette rein, welches nur schaut "gehts über 0dB" und wenn ja, die Position mitloggt.
Nach dem Rendern bieten wir an "Es gab Clippings beim Rendern, willste die anzeigen um zu wissen, wo nachzubessern ist?"

Das wäre ein Killerfeature, auch über Ultraschall hinaus. Eines der immer wieder gewünschten Features im Reaper-Forum...

**Comment by fernsehmuell** [comment]
Kann ein JSFX den Timecode lesen?

**Comment by mespotine** [comment]
Also den Sekundenstand im Projekt? Müsste, um für Sampling-Sachen den Sample-Abspiel-Speed anpassen zu können...

Hab mir das aber nie angeschaut...

**Comment by mespotine** [comment]
[](https://www.reaper.fm/sdk/js/vars.php#js_specialvars)

> play_position
> Context: @block, @sample
> Usage: read-only
> The current playback position in REAPER (as of last @block), in seconds.

**Comment by rstockm** [comment]
Wird vermutlich effektiv durch https://github.com/Ultraschall/ultraschall-portable/issues/332 gelöst.
Ansonsten zur 5.0

**Comment by mespotine** [comment]
Wird Reaper in den aktuellsten 7er Versionen lösen.
