### ISSUE TITLE
JSFX Filter für Audiopegelerfassung

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#53]
JSFX Filter, das die den Audiopegel erfasst und in eine Textdatei schreibt. Diese kann später für einen Bericht ausgewertet werden.

**Comment by mespotine** [comment]
Reaper kann mit der 7er solche Auswertungen selbst machen, inklusive eines Protokolls. Daher ist die Idee obsolet.
