### ISSUE TITLE
CMD Drag sollte sich wie Drag mit Ripple-All-Tracks verhalten

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#54]
So spart man sich den Ripple Modus an- und wieder aus zuschalten.
Derzeit liegt auf CMD-Drag "copy item" was man für den Podcastschnitt eh nie braucht.
Mouse Modifier -> Media Item, left Drag -> Move item ignoring time selection, enabling ripple edit for all tracks

Ich finde ein Megafeature! :-)

**Comment by mespotine** [comment]
Bin nicht so sicher ob man das so einschalten kann. Für Dragging kann man leider keine Actions selber schreiben, nur vorgefertigte kann man nutzen.

**Comment by rstockm** [comment]
Erledigt in

https://github.com/Ultraschall/ultraschall-portable/commit/ce4787865e594deccab5f0a02a9e488ab09fef45
