### ISSUE TITLE
Ripple Cut und vorhandene Punkte in der Envelope Spur (mute)

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#58]
Schneidet man mit dem Ripple Cut (CMD+X) und es gibt in der Envelope Mute-Spur Punkte, kann es dazu führen, dass danach zuviel stumm geschalltet wird. Man müsste wahrscheinlich nur am Anfang und Ende der Auswahl neue Punkte anlegen.

**Comment by mespotine** [comment]
Vermutlich sollten wir da alle Envelopes durchgehen, oder?
