### ISSUE TITLE
ultraclock.lua umbenennen

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#6]
In der 3.1 Distribution gibt es zwei Dateien der Ultraclock - über die Screensets aufgerufen wird ultracklock.lua. Dateien konsolidieren und zu ultraschall_ultraclock.lua zusammenführen.

**Comment by fernsehmuell** [comment]
Es gibt die ultraclock.lua und die ultraschall_ultraclock.lua. Die Dateien sind identisch (MD5 ist gleich).
Ich werde die ultraclock.lua löschen und alle Verweise darauf (reaper.ini und reaper-kb.ini umbenennen bzw.. löschen).

**Comment by fernsehmuell** [comment]
Pull Request #25
