### ISSUE TITLE
Undo beim Color Picker

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#63]
Der Color Picker bzw. seine Einfärbungen sollen Undo-Robust gebaut sein.

**Comment by fernsehmuell** [comment]
Ich habe das mal in den branch 63-colorpicker-undo eingebaut. Im Prinzip ganz einfach in der GUI-lib den Teil, der die Farbe ändert in einen UNDO-Block gesetzt.
