### ISSUE TITLE
CMD+M setzt bei Stop Pause an falsche Stelle

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#64]
CMD+m soll die Kapitelmarke immer an die Play-Position setzen. Das funktioniert während der Aufnahme gut, wenn diese jedoch pausiert oder im Stop-Modus ist, wird zwar sichtbar der Play-Cursor an den Edit-Cursor gesetzt, das Skript setzt die Marke jedoch an die letzte bekannte Play-Position davor.
Gewünschtes Verhalten: Marker werden immer an die sichtbare Position des Play-Cursors gesetzt.
Betrifft vermutlich auch cmd+e und cmd+shift+m

**Comment by mespotine** [comment]
Verstehe ich nicht so ganz. Soll bei Stop und Pause der Marker an die Edit oder Playposition gesetzt werden?

**Comment by fernsehmuell** [comment]
Habe es mal so gemacht, dass der Marker bei Pause an die Edit-Cursor Position gesetzt wird. Habe das gleich bei allen Marker-Skripten geändert, bitte alle nochmal checken.
