### ISSUE TITLE
Mousemodifier sind verlorengegangen

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#65]
In einem der letzten Commits sind die Mouse-Modifier verloren gegangen, sprich kein DoppelKlick für Play und Ähnliches.

Zum Fixen müsste die reaper-mouse.ini mal auf einen früheren Stand reverted werden, wo es noch _ULTRASCHALL_COMMAND_IDs drin gibt.

**Comment by lootsy** [comment]
> wo es noch _ULTRASCHALL_COMMAND_IDs drin gibt.

Wie kann ich denn feststellen, welche Command Ids du _genau_ meinst, und ob die dann nachher wieder vollständig drin sind?

Wenn die Änderungen [dieses Commits](https://github.com/Ultraschall/ultraschall-portable/commit/2230c86e80d6927f85065a5e8694f09934fe17cd#diff-2211c3d63455a9d35c023fb0f48018d6) an der reaper-mouse.ini rückgängig gemacht werden, ist das dann wieder ok?

**Comment by lootsy** [comment]
Ich hab mir jetzt die komplette Änderungshistorie von `reaper-mouse.ini` angesehen.

> Wie kann ich denn feststellen, welche Command Ids du _genau_ meinst, und ob die dann nachher wieder vollständig drin sind?
> 
> Wenn die Änderungen [dieses Commits](https://github.com/Ultraschall/ultraschall-portable/commit/2230c86e80d6927f85065a5e8694f09934fe17cd#diff-2211c3d63455a9d35c023fb0f48018d6) an der reaper-mouse.ini rückgängig gemacht werden, ist das dann wieder ok?

Da ich die von REAPER und Ultraschall keine Ahnung habe, kann ich nicht beurteilen, welche Zeilen von dem o. g. Commit sinnvoll sind und welche nicht.
Ich mach jetzt mal - weil ich es nicht besser weiß - alles wieder zurück.

**Comment by lootsy** [comment]
Hoffe, dass der [PR 66](https://github.com/Ultraschall/ultraschall-portable/pull/66) das Problem löst.

Habe mal meo und Ralf als Reviewer eingetragen ("requested").

**Comment by rstockm** [comment]
Die anderen Änderungen sehen gut aus. Bei der reaper.ini sollte lasttheme leer sein, das ist aber auch nicht so rasend kritisch.
