### ISSUE TITLE
Aufnahmeposition wird an die letzte Playposition gesetzt

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#67]
![recbug](https://user-images.githubusercontent.com/3195116/52112859-1a0a7e80-2608-11e9-973e-0a0abbe9b9fe.gif)

Wenn ich eine Aufnahme stoppe, mir zur Kontrolle einen Teil davon anhöre, dann wieder mit dem Cursor zum Ende der Aufnahme springe und dort die Aufnahme fortfahre, wird die Aufnahme über die letzte Play-Position gelegt.

Erwartetes Verhalten: Die Aufnahme beginnt immer an der Stelle des Edit-Cursors

**Comment by fernsehmuell** [comment]
Ich habe das Problem verstanden. Eigentlich eine Feature: wenn du im Play/Pause Modus bist, wird immer am letzen Punkt die Aufnahme fortgesetzt. Um das zu umgehen, reicht eine Custom Action, die erst Stop und dann Rec. aufruft, statt direkt Rec. Ich mache daraus jetzt erstmal keinen Pullrequest, weil du ja in der Ini-Datei was tun musst.

**Comment by fernsehmuell** [comment]
Da wir den Rec-Button nicht ersetzen können (was eigentlich voll blöd ist!) könnte das noch im Hintergrund-Check mit abgebildet werden. Wenn jemand Rec. drückt, springe immer ans Ende. Oder ist das vielleicht schon so @rstockm ?

**Comment by mespotine** [comment]
Hmm...fänd ich eher unglücklich. Es kann durchaus gute Gründe dafür geben in der Mitte des Projekts Aufnahme starten zu wollen.
Wenn Du dann vergessen hast den Check auf ignore zu stellen, würde die Aufnahme erstmal an die vollkommen falsche Stelle springen.

Die Warnung find ich gut, aber eigenmächtig zu entscheiden, wohin nun weiter aufgenommen werden soll find ich echt problematisch. Das sollen die Nutzenden entscheiden. Ist ja schließlich deren Projekt.

**Comment by mespotine** [comment]
Meiner Erinnerung nach, stoppt der Soundcheck derzeit die Aufnahme dann einfach sofort wieder.

**Comment by rstockm** [comment]
Das sind zwei verschiedene Probleme. Das eine - aus Versehen starte ich eine Aufnahme nicht am Ende - wird durch den Soundcheck m.E. jetzt elegant abgefangen.

Das von mir oben beschriebene Verhalten ist aber ein ganz anderes Problem. Bitte nochmal nachtesten/reindenken (im Branch Magicrouting). Das fängt der Soundcheck jetzt nur so semigut ab.

**Comment by fernsehmuell** [comment]
Das Problem ist, wenn ich das richtig gesehen habe gelöst mit dem neuen Soundcheck "Start Recording only at the End" kann also als gelöst weg.
