### ISSUE TITLE
Usernamen mit Umlauten auf Windows macht Probleme!

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-portable#71]
Folgendes heute in freier Wildbahn gedebuggt: Ein Benutzer mit Umlaut im Windows-Useramen: "Björn" macht, dass die Ultraclock sich sofort beendet.
Schuld ist der Rückgabewert dieser Zeile code:

count, view = ultraschall.GetUSExternalState("ultraschall_gui", "view") -- get the actual view

Die Variable Count enthält 2, aber view ist nicht "record", sondern "-1"

Wir haben einen zweiten User erstellt ohne Umlaute, da ging es sofort.

**Comment by mespotine** [comment]
Problem identifiziert. Es sind die SWS-Get/WriteProfileString-Funktionen. Habs gemeldet als BugReport aber auch schon ne Neuimplementation der Funktionen gebastelt. Wird die Tage mal ins Portable-Repo wandern mit ein paar neuen API-Features.

**Comment by mespotine** [comment]
Wird gelöst durch #77 

Löst dadurch auch #19

**Comment by mespotine** [comment]
erledigt.
