### ISSUE TITLE
Ripple-Insert-Recording - fügt eine neue Aufnahme ins Projekt ein

### ISSUE THREAD

**Issue by mespotine** [Ultraschall/ultraschall-portable#72]
Das hab ich schon länger rumliegen: Ripple Insert Recording.

Wenn man im Projekt ist und Ripple Insert Recordin startet, dann fügt er die Aufnahme ins Projekt ein.

Dazu schneidet er an der Aufnahmeposition über alle Tracks die Audio durch und verschiebt alles danach kommende nach hinten, solange die Aufnahme läuft.
Stoppt man die Aufnahme, schiebt er alles ran, so dass keine Lücke entsteht.

Das ist wie, als hat man RippleEdit an und schiebt ein AudioItem irgendwo ins Projekt rein. 
![rippleinsertrecording](https://user-images.githubusercontent.com/4251851/52492517-afd67880-2bc9-11e9-9f0e-d5a521163d3a.gif)

**Comment by rstockm** [comment]
Gelöst durch: https://github.com/Ultraschall/ultraschall-portable/commit/b88f31e97a8dd0042dc59f5a28fc2f6a1d8aaa69
