### ISSUE TITLE
Shift+Click in Timeline erweitert Zeitauswahl

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#84]
Ich höre die Aufnahme, dann kommt eine Denkpause, die ich gern verkürzen möchte. Dazu lasse ich den Player weiterlaufen, bis zum Ende dessen, was ich löschen möchte und drücke die Leertaste, um den Player zu stoppen.

Nun halte ich [Shift] gedrückt und klicke auf den Anfang der zu löschenden Stelle, in der Erwartung, dass nun der Bereich vom Playhead bis zum Curser ausgewählt wird.

Lösung: lässt sich gut über Mouse Modifiers einstellen und kollidiert auch mit keinem bereits vorhandenen Setting.

**Comment by mespotine** [comment]
Duplicate mit #8
