### ISSUE TITLE
First Start: Setzen einer sinnvollen Fenstergröße

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#89]
Um das Onboarding zu verbessern, sollten wir beim allerersten Start - und nur dann, da haben wir schon eine Condition für - prüfen welche Auflösung der Screen hat und irgendwie(tm) das Reaperfenster entsprechend auf eine sinnvolle Größe setzen.

**Comment by mespotine** [comment]
Duplicate mit #2
