### ISSUE TITLE
Zoom Limiter für sehr kurze Projekte

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-portable#90]
der zoom Limiter produziert derzeit noch ein Problem bei neuen Aufnahmen. Vorgehen: ich starte ein leeres Projekt, der Zoom ist recht weit draußen. Ich starte die Aufnahme, der Aufnahmebalken kriecht nur wenig von der Stelle. Ich zoome rein um zu schauen, dass da wirklich alles seine Ordnung hat - und kann nicht mehr zurück zoomen auf eine mittlere Stufe, da das Projekt eben noch sehr kurz ist.
Man kann natürlich mit `alt`+`zoom` das umgehen, besser wäre es aber, eine sinnvolle Untergrenze zu definieren unter der der Zoomlimiter nicht zuschlägt. Sprich - man kann immer bis 5 Minuten rauszoomen oder so was.

**Comment by mespotine** [comment]
Bereits erledigt.
